const WIZARD_KEY = 'universal-video-wizard-state';
const CONSULTANT_KEY = 'universal-video-consultant-state';
const DRAFT_VERSION = 2;

export interface WizardDraft {
  category: string | null;
  mode: string | null;
  step: number;
  moodConfig: any;
  consultationResult: any;
  autoGeneratedProject: any;
  updatedAt: string;
  version: number;
}

export interface ConsultantDraft {
  category: string;
  mode: string;
  messages: any[];
  progress: number;
  lastRecommendation: any;
  showModeChoice: boolean;
  updatedAt: string;
  version: number;
}

function safeParse<T>(key: string): T | null {
  try {
    const raw = localStorage.getItem(key);
    if (!raw) return null;
    const parsed = JSON.parse(raw);
    // Reject old versions
    if (parsed.version && parsed.version < DRAFT_VERSION) {
      localStorage.removeItem(key);
      return null;
    }
    return parsed as T;
  } catch {
    localStorage.removeItem(key);
    return null;
  }
}

export function getWizardDraft(): WizardDraft | null {
  return safeParse<WizardDraft>(WIZARD_KEY);
}

export function getConsultantDraft(): ConsultantDraft | null {
  return safeParse<ConsultantDraft>(CONSULTANT_KEY);
}

export function saveWizardDraft(data: Omit<WizardDraft, 'updatedAt' | 'version'>) {
  localStorage.setItem(WIZARD_KEY, JSON.stringify({
    ...data,
    updatedAt: new Date().toISOString(),
    version: DRAFT_VERSION,
  }));
}

export function saveConsultantDraft(data: Omit<ConsultantDraft, 'updatedAt' | 'version'>) {
  localStorage.setItem(CONSULTANT_KEY, JSON.stringify({
    ...data,
    updatedAt: new Date().toISOString(),
    version: DRAFT_VERSION,
  }));
}

export function clearAllDrafts() {
  localStorage.removeItem(WIZARD_KEY);
  localStorage.removeItem(CONSULTANT_KEY);
}

export function hasMeaningfulDraft(): boolean {
  const wizard = getWizardDraft();
  const consultant = getConsultantDraft();
  
  // Has wizard progress beyond category selection
  if (wizard && (wizard.step > 0 || wizard.consultationResult)) return true;
  
  // Has consultant messages beyond the initial one
  if (consultant && consultant.messages?.length > 1) return true;
  
  return false;
}
