import { scopedDraftKey, migrateLegacyDraftKey } from '@/lib/local-draft-scope';

const WIZARD_BASE_KEY = 'universal-video-wizard-state';
const CONSULTANT_BASE_KEY = 'universal-video-consultant-state';

/** Drafts are bound to the signed-in account, never shared across logins. */
const wizardKey = () => {
  migrateLegacyDraftKey(WIZARD_BASE_KEY);
  return scopedDraftKey(WIZARD_BASE_KEY);
};
const consultantKey = () => {
  migrateLegacyDraftKey(CONSULTANT_BASE_KEY);
  return scopedDraftKey(CONSULTANT_BASE_KEY);
};
const DRAFT_VERSION = 3;

export interface WizardDraft {
  category: string | null;
  mode: string | null;
  step: number;
  stepId: string | null;
  moodConfig: any;
  consultationResult: any;
  autoGeneratedProject: any;
  updatedAt: string;
  version: number;
}

export interface ConsultantDraft {
  category: string;
  mode: string;
  messages: any[];
  progress: number;
  lastRecommendation: any;
  showModeChoice: boolean;
  updatedAt: string;
  version: number;
}

function safeParse<T>(key: string): T | null {
  try {
    const raw = localStorage.getItem(key);
    if (!raw) return null;
    const parsed = JSON.parse(raw);
    // Reject old versions
    if (!parsed.version || parsed.version < DRAFT_VERSION) {
      localStorage.removeItem(key);
      return null;
    }
    return parsed as T;
  } catch {
    localStorage.removeItem(key);
    return null;
  }
}

export function getWizardDraft(): WizardDraft | null {
  return safeParse<WizardDraft>(wizardKey());
}

export function getConsultantDraft(): ConsultantDraft | null {
  return safeParse<ConsultantDraft>(consultantKey());
}

export function saveWizardDraft(data: Omit<WizardDraft, 'updatedAt' | 'version'>) {
  localStorage.setItem(wizardKey(), JSON.stringify({
    ...data,
    updatedAt: new Date().toISOString(),
    version: DRAFT_VERSION,
  }));
}

export function saveConsultantDraft(data: Omit<ConsultantDraft, 'updatedAt' | 'version'>) {
  localStorage.setItem(consultantKey(), JSON.stringify({
    ...data,
    updatedAt: new Date().toISOString(),
    version: DRAFT_VERSION,
  }));
}

export function clearAllDrafts() {
  localStorage.removeItem(wizardKey());
  localStorage.removeItem(consultantKey());
}

export function hasMeaningfulDraft(): boolean {
  const wizard = getWizardDraft();
  const consultant = getConsultantDraft();
  
  // Has wizard progress beyond category selection
  if (wizard && (wizard.step > 0 || wizard.consultationResult)) return true;
  
  // Has consultant messages beyond the initial one
  if (consultant && consultant.messages?.length > 1) return true;
  
  return false;
}
