// auto-director-compose v1.0.0 — 1-Click AI Movie Generator
// Orchestrates: AI plan → scene insert → parallel clip generation → optional voiceover/music
import { serve } from "https://deno.land/std@0.224.0/http/server.ts";
import { createClient } from "https://esm.sh/@supabase/supabase-js@2";

const corsHeaders = {
  "Access-Control-Allow-Origin": "*",
  "Access-Control-Allow-Headers": "authorization, x-client-info, apikey, content-type",
};

type Mood = 'cinematic' | 'hype' | 'calm' | 'corporate' | 'playful' | 'dramatic';
type EnginePref = 'auto' | 'premium' | 'budget';
type Stage = 'plan' | 'execute';

interface AutoDirectorRequest {
  stage: Stage;                 // 'plan' = preview only, 'execute' = create project + clips
  projectId?: string;           // required for stage=execute when re-using preview
  idea: string;
  mood: Mood;
  targetDurationSec: number;    // 15 | 30 | 60
  enginePreference?: EnginePref;
  language?: string;
  // execute-only:
  approvedScenes?: PlannedScene[];
  voicePreset?: string | null;
  musicMood?: string | null;
  title?: string;
}

interface PlannedScene {
  orderIndex: number;
  sceneType: string;
  durationSeconds: number;
  aiPrompt: string;
  textOverlay?: { text: string; position: 'top' | 'center' | 'bottom' } | null;
  recommendedEngine: string; // 'ai-hailuo' | 'ai-kling' | ...
}

interface PlanResult {
  scenes: PlannedScene[];
  estimatedCostEuros: number;
  rationale: string;
  brandContext?: BrandContext | null;
}

interface BrandContext {
  brandName: string | null;
  primaryColor: string | null;
  secondaryColor: string | null;
  mood: string | null;
  brandTone: string | null;
  brandValues: string[];
}

const ENGINE_BY_PREF: Record<EnginePref, string[]> = {
  auto:    ['ai-hailuo', 'ai-seedance', 'ai-wan', 'ai-kling', 'ai-luma'],
  premium: ['ai-kling', 'ai-luma', 'ai-sora'],
  budget:  ['ai-wan', 'ai-seedance', 'ai-hailuo'],
};

// Cost per second per engine (standard quality, mirrors compose-video-clips)
const COST_PER_SEC: Record<string, number> = {
  'ai-hailuo': 0.15, 'ai-kling': 0.15, 'ai-sora': 0.25,
  'ai-wan': 0.10, 'ai-seedance': 0.12, 'ai-luma': 0.20,
};

serve(async (req) => {
  if (req.method === "OPTIONS") return new Response(null, { headers: corsHeaders });

  try {
    const authHeader = req.headers.get("Authorization");
    if (!authHeader) {
      return jsonResponse({ error: "UNAUTHORIZED", message: "Missing Authorization header" }, 401);
    }

    const supabaseClient = createClient(
      Deno.env.get("SUPABASE_URL") ?? "",
      Deno.env.get("SUPABASE_ANON_KEY") ?? ""
    );
    const token = authHeader.replace("Bearer ", "");
    const { data: { user }, error: authError } = await supabaseClient.auth.getUser(token);
    if (authError || !user) {
      return jsonResponse({ error: "UNAUTHORIZED" }, 401);
    }

    const supabaseAdmin = createClient(
      Deno.env.get("SUPABASE_URL") ?? "",
      Deno.env.get("SUPABASE_SERVICE_ROLE_KEY") ?? ""
    );

    const body: AutoDirectorRequest = await req.json();
    const stage = body.stage ?? 'plan';

    // Input validation
    if (!body.idea || body.idea.trim().length < 5) {
      return jsonResponse({ error: "INVALID_INPUT", message: "idea must be at least 5 characters" }, 400);
    }
    if (![15, 30, 60].includes(body.targetDurationSec)) {
      return jsonResponse({ error: "INVALID_INPUT", message: "targetDurationSec must be 15, 30 or 60" }, 400);
    }

    // ============== STAGE 1: PLAN ==============
    if (stage === 'plan') {
      const brandContext = await loadActiveBrandContext(supabaseAdmin, user.id);
      const plan = await generateScenePlan(body, brandContext);
      return jsonResponse({ ok: true, plan: { ...plan, brandContext } });
    }

    // ============== STAGE 2: EXECUTE ==============
    const scenes = body.approvedScenes;
    if (!scenes || scenes.length === 0) {
      return jsonResponse({ error: "MISSING_SCENES", message: "approvedScenes is required for execute stage" }, 400);
    }

    // Create new composer project
    const config = {
      idea: body.idea,
      mood: body.mood,
      targetDurationSec: body.targetDurationSec,
      sceneCount: scenes.length,
      enginePreference: body.enginePreference ?? 'auto',
      voicePreset: body.voicePreset ?? null,
      musicMood: body.musicMood ?? null,
      generatedAt: new Date().toISOString(),
    };

    const totalEstimatedCost = scenes.reduce(
      (sum, s) => sum + (COST_PER_SEC[s.recommendedEngine] ?? 0.15) * s.durationSeconds,
      0
    );

    const { data: project, error: projErr } = await supabaseAdmin
      .from('composer_projects')
      .insert({
        user_id: user.id,
        title: body.title || `Auto: ${body.idea.slice(0, 50)}`,
        category: 'custom',
        briefing: { idea: body.idea, mood: body.mood, autoGenerated: true },
        status: 'generating',
        storyboard: [],
        assembly_config: {},
        total_cost_euros: 0,
        language: body.language ?? 'de',
        auto_director_config: config,
      })
      .select()
      .single();

    if (projErr || !project) {
      console.error('[auto-director] project insert failed:', projErr);
      return jsonResponse({ error: "DB_ERROR", message: projErr?.message ?? "Failed to create project" }, 500);
    }

    // Bulk insert scenes
    const sceneRows = scenes.map((s) => ({
      project_id: project.id,
      order_index: s.orderIndex,
      scene_type: s.sceneType,
      duration_seconds: s.durationSeconds,
      clip_source: s.recommendedEngine,
      ai_prompt: s.aiPrompt,
      clip_status: 'pending',
      text_overlay: s.textOverlay ?? {},
      transition_type: 'fade',
      transition_duration: 0.5,
      clip_quality: 'standard',
      cost_euros: (COST_PER_SEC[s.recommendedEngine] ?? 0.15) * s.durationSeconds,
    }));

    const { data: insertedScenes, error: scenesErr } = await supabaseAdmin
      .from('composer_scenes')
      .insert(sceneRows)
      .select();

    if (scenesErr) {
      // rollback project
      await supabaseAdmin.from('composer_projects').delete().eq('id', project.id);
      console.error('[auto-director] scenes insert failed:', scenesErr);
      return jsonResponse({ error: "DB_ERROR", message: scenesErr.message }, 500);
    }

    // Trigger compose-video-clips asynchronously (fire-and-forget — caller polls scene status)
    const clipsPayload = {
      projectId: project.id,
      scenes: (insertedScenes ?? []).map((s: any) => ({
        id: s.id,
        clipSource: s.clip_source,
        clipQuality: s.clip_quality,
        aiPrompt: s.ai_prompt,
        durationSeconds: Number(s.duration_seconds),
      })),
    };

    // Async invoke without awaiting result — clips run in background
    supabaseClient.functions.invoke('compose-video-clips', {
      body: clipsPayload,
      headers: { Authorization: authHeader },
    }).catch((err) => {
      console.error('[auto-director] async clips invoke error:', err);
    });

    return jsonResponse({
      ok: true,
      projectId: project.id,
      sceneCount: scenes.length,
      estimatedCostEuros: Number(totalEstimatedCost.toFixed(4)),
      message: 'Auto-Director project created. Clips are generating in the background.',
    });

  } catch (err) {
    const msg = err instanceof Error ? err.message : 'Unknown error';
    console.error('[auto-director] error:', msg);
    return jsonResponse({ error: "INTERNAL_ERROR", message: msg }, 500);
  }
});

// ============================================================================
// AI PLAN GENERATION via Lovable AI Gateway (Gemini 2.5 Pro with structured tool calling)
// ============================================================================
async function generateScenePlan(req: AutoDirectorRequest): Promise<PlanResult> {
  const LOVABLE_API_KEY = Deno.env.get("LOVABLE_API_KEY");
  if (!LOVABLE_API_KEY) {
    throw new Error("LOVABLE_API_KEY is not configured");
  }

  const enginePref = req.enginePreference ?? 'auto';
  const allowedEngines = ENGINE_BY_PREF[enginePref];
  const targetSec = req.targetDurationSec;
  // Aim for 4-6 second scenes → derive scene count
  const idealSceneCount = Math.max(2, Math.min(8, Math.round(targetSec / 5)));

  const systemPrompt = `You are an expert AI video director. Your job is to transform a single idea into a compelling video storyboard.

RULES:
- Generate EXACTLY ${idealSceneCount} scenes that together total ~${targetSec} seconds.
- Each scene duration: 3-8 seconds (preferably 4-6).
- Each ai_prompt must be a vivid, cinematic visual description (camera angle, subject, action, lighting, mood) — NO dialogue, NO subtitles in the prompt.
- Keep prompts concise (15-30 words each), suitable for AI video generation models.
- Use the requested mood "${req.mood}" to drive style (e.g. cinematic = wide angles & dramatic lighting; hype = fast cuts & bold colors; calm = slow pans & soft tones; corporate = clean & professional; playful = bright & dynamic; dramatic = high contrast & tension).
- Choose recommended_engine ONLY from this list: ${allowedEngines.join(', ')}.
- Pick the best engine per scene: ai-kling/ai-luma for character close-ups & dialogue feel, ai-hailuo for fast action, ai-seedance for stylish motion, ai-wan for budget shots, ai-sora for hero moments.
- Scene types: hook, problem, solution, feature, proof, cta, intro, outro, transition.
- Output language for any text_overlay: ${req.language ?? 'de'}.
- Add a short text_overlay (3-6 words) ONLY on hook and cta scenes.`;

  const userPrompt = `Idea: "${req.idea}"
Mood: ${req.mood}
Total duration target: ${targetSec}s
Engine preference: ${enginePref}

Create the storyboard now.`;

  const response = await fetch("https://ai.gateway.lovable.dev/v1/chat/completions", {
    method: "POST",
    headers: {
      Authorization: `Bearer ${LOVABLE_API_KEY}`,
      "Content-Type": "application/json",
    },
    body: JSON.stringify({
      model: "google/gemini-2.5-pro",
      messages: [
        { role: "system", content: systemPrompt },
        { role: "user", content: userPrompt },
      ],
      tools: [{
        type: "function",
        function: {
          name: "create_storyboard",
          description: "Return the structured scene plan",
          parameters: {
            type: "object",
            properties: {
              rationale: { type: "string", description: "1-2 sentence summary of the creative direction" },
              scenes: {
                type: "array",
                minItems: 2,
                maxItems: 8,
                items: {
                  type: "object",
                  properties: {
                    order_index: { type: "integer" },
                    scene_type: {
                      type: "string",
                      enum: ['hook', 'problem', 'solution', 'feature', 'proof', 'cta', 'intro', 'outro', 'transition', 'custom'],
                    },
                    duration_seconds: { type: "number", minimum: 3, maximum: 8 },
                    ai_prompt: { type: "string" },
                    recommended_engine: { type: "string", enum: allowedEngines as unknown as string[] },
                    text_overlay: {
                      type: ["object", "null"],
                      properties: {
                        text: { type: "string" },
                        position: { type: "string", enum: ['top', 'center', 'bottom'] },
                      },
                    },
                  },
                  required: ["order_index", "scene_type", "duration_seconds", "ai_prompt", "recommended_engine"],
                  additionalProperties: false,
                },
              },
            },
            required: ["rationale", "scenes"],
            additionalProperties: false,
          },
        },
      }],
      tool_choice: { type: "function", function: { name: "create_storyboard" } },
    }),
  });

  if (!response.ok) {
    if (response.status === 429) throw new Error("AI rate limit reached, please try again in a moment.");
    if (response.status === 402) throw new Error("AI credits exhausted — please top up Lovable AI credits.");
    const errText = await response.text();
    throw new Error(`AI gateway error ${response.status}: ${errText.slice(0, 200)}`);
  }

  const data = await response.json();
  const toolCall = data.choices?.[0]?.message?.tool_calls?.[0];
  if (!toolCall?.function?.arguments) {
    throw new Error("AI did not return a structured plan");
  }

  let parsed: { rationale: string; scenes: any[] };
  try {
    parsed = JSON.parse(toolCall.function.arguments);
  } catch {
    throw new Error("Failed to parse AI plan output");
  }

  const scenes: PlannedScene[] = parsed.scenes.map((s: any, idx: number) => ({
    orderIndex: typeof s.order_index === 'number' ? s.order_index : idx,
    sceneType: s.scene_type,
    durationSeconds: Number(s.duration_seconds),
    aiPrompt: String(s.ai_prompt),
    recommendedEngine: allowedEngines.includes(s.recommended_engine) ? s.recommended_engine : allowedEngines[0],
    textOverlay: s.text_overlay && s.text_overlay.text ? {
      text: String(s.text_overlay.text),
      position: (['top','center','bottom'].includes(s.text_overlay.position) ? s.text_overlay.position : 'bottom') as 'top'|'center'|'bottom',
    } : null,
  }));

  const estimatedCostEuros = scenes.reduce(
    (sum, s) => sum + (COST_PER_SEC[s.recommendedEngine] ?? 0.15) * s.durationSeconds,
    0
  );

  return {
    scenes,
    estimatedCostEuros: Number(estimatedCostEuros.toFixed(4)),
    rationale: parsed.rationale ?? '',
  };
}

function jsonResponse(payload: unknown, status = 200): Response {
  return new Response(JSON.stringify(payload), {
    status,
    headers: { ...corsHeaders, "Content-Type": "application/json" },
  });
}
