// Function Smoke Matrix — Registry of safely-sweepable edge functions.
//
// Each entry describes how to call ONE edge function with a deterministic
// mock payload so the Bond-QA Function Matrix can verify it returns 200 +
// the expected shape. NEVER add functions that mutate user data without
// a working `x-qa-mock` short-circuit.
//
// Categories drive grouping in the Cockpit UI.

export type SmokeStatusExpect = "any-2xx" | "ok-flag" | "structured";

export interface SmokeEntry {
  /** Edge function name (folder name under supabase/functions/). */
  name: string;
  category:
    | "admin-cron-1"
    | "admin-cron-2"
    | "ai-text-generation"
    | "ai-video-providers"
    | "analytics-reports"
    | "audio-music-sfx-1"
    | "audio-music-sfx-2"
    | "automation-jobs-1"
    | "automation-jobs-2"
    | "billing-credits"
    | "briefing-composer"
    | "briefing-director"
    | "calendar-planning"
    | "community-coach"
    | "composer-render"
    | "data-fetch"
    | "image-providers"
    | "lipsync-dialog"
    | "misc-1"
    | "misc-2"
    | "misc-3"
    | "notifications-email"
    | "picture-image-1"
    | "picture-image-2"
    | "planner-strategy"
    | "qa-testing"
    | "social-google"
    | "social-meta"
    | "social-other"
    | "social-publishing"
    | "social-tiktok-twitch"
    | "utilities"
    | "misc";
  /** Body sent in the test request. */
  body?: Record<string, unknown>;
  /** Extra headers (x-qa-mock is added automatically). */
  headers?: Record<string, string>;
  /** Loose expectation: status code OR JSON field presence. */
  expect?: SmokeStatusExpect;
  /** If true, function is skipped automatically with the given reason. */
  skip?: string;
  /** Soft per-call timeout in ms. Default 8000. */
  timeoutMs?: number;
}

// Helper UUIDs for mock payloads (never written to DB in mock mode).
const MOCK_UUID = "00000000-0000-0000-0000-000000000001";
const MOCK_IMAGE = "https://storage.googleapis.com/lovable-public/qa-mock/sample-1024.jpg";
const MOCK_AUDIO = "https://storage.googleapis.com/lovable-public/qa-mock/sample-5s.mp3";

export const SMOKE_REGISTRY: SmokeEntry[] = [
  { name: "generate-ai-video",                category: "ai-video-providers", body: { prompt: "qa", duration: 5 }, expect: "any-2xx" },
  { name: "generate-fast-preview",            category: "ai-video-providers", body: { prompt: "qa" }, expect: "any-2xx" },
  {
    name: "generate-grok-video",
    category: "ai-video-providers",
    body: { prompt: "a cat walking", duration: 5 },
    expect: "ok-flag",
  },
  {
    name: "generate-hailuo-video",
    category: "ai-video-providers",
    body: { prompt: "a cat walking", duration: 6, resolution: "768p" },
    expect: "ok-flag",
  },
  {
    name: "generate-happyhorse-video",
    category: "ai-video-providers",
    body: { prompt: "a cat walking", duration: 5, resolution: "720p" },
    expect: "ok-flag",
  },
  {
    name: "generate-kling-video",
    category: "ai-video-providers",
    body: { prompt: "a cat walking", duration: 5 },
    expect: "ok-flag",
  },
  {
    name: "generate-ltx-video",
    category: "ai-video-providers",
    body: { prompt: "a cat walking", duration: 5 },
    expect: "ok-flag",
  },
  {
    name: "generate-luma-video",
    category: "ai-video-providers",
    body: { prompt: "a cat walking", duration: 5 },
    expect: "ok-flag",
  },
  {
    name: "generate-pika-video",
    category: "ai-video-providers",
    body: { prompt: "a cat walking", duration: 5 },
    expect: "ok-flag",
  },
  {
    name: "generate-runway-video",
    category: "ai-video-providers",
    body: { prompt: "a cat walking", duration: 5 },
    expect: "ok-flag",
  },
  {
    name: "generate-seedance-video",
    category: "ai-video-providers",
    body: { prompt: "a cat walking", duration: 5 },
    expect: "ok-flag",
  },
  {
    name: "generate-veo-video",
    category: "ai-video-providers",
    body: { prompt: "a cat walking", duration: 5 },
    expect: "ok-flag",
  },
  { name: "generate-video-variants",          category: "ai-video-providers", body: { prompt: "qa" }, expect: "any-2xx" },
  {
    name: "generate-vidu-video",
    category: "ai-video-providers",
    body: { prompt: "a cat walking", duration: 5 },
    expect: "ok-flag",
  },
  {
    name: "generate-wan-video",
    category: "ai-video-providers",
    body: { prompt: "a cat walking", duration: 5 },
    expect: "ok-flag",
  },
  {
    name: "animate-scene-hailuo",
    category: "lipsync-dialog",
    body: { sceneId: MOCK_UUID, prompt: "test" },
    expect: "ok-flag",
  },
  { name: "cancel-dialog-lipsync", category: "lipsync-dialog", body: { videoUrl: "https://storage.googleapis.com/lovable-public/qa-mock/sample-5s.mp4", audioUrl: "https://storage.googleapis.com/lovable-public/qa-mock/sample-5s.mp3" }, expect: "any-2xx" },
  {
    name: "compose-scene-anchor",
    category: "lipsync-dialog",
    body: { sceneId: MOCK_UUID, portraitUrls: [MOCK_IMAGE] },
    expect: "ok-flag",
  },
  {
    name: "lip-sync-video",
    category: "lipsync-dialog",
    body: { videoUrl: "https://example.com/v.mp4", audioUrl: MOCK_AUDIO },
    expect: "ok-flag",
  },
  { name: "lipsync-watchdog", category: "lipsync-dialog", body: { videoUrl: "https://storage.googleapis.com/lovable-public/qa-mock/sample-5s.mp4", audioUrl: "https://storage.googleapis.com/lovable-public/qa-mock/sample-5s.mp3" }, expect: "any-2xx" },
  { name: "sync-so-webhook", category: "lipsync-dialog", body: { videoUrl: "https://storage.googleapis.com/lovable-public/qa-mock/sample-5s.mp4", audioUrl: "https://storage.googleapis.com/lovable-public/qa-mock/sample-5s.mp3" }, expect: "any-2xx" },
  { name: "sync-social-posts", category: "lipsync-dialog", body: { videoUrl: "https://storage.googleapis.com/lovable-public/qa-mock/sample-5s.mp4", audioUrl: "https://storage.googleapis.com/lovable-public/qa-mock/sample-5s.mp3" }, expect: "any-2xx" },
  { name: "sync-social-posts-v2", category: "lipsync-dialog", body: { videoUrl: "https://storage.googleapis.com/lovable-public/qa-mock/sample-5s.mp4", audioUrl: "https://storage.googleapis.com/lovable-public/qa-mock/sample-5s.mp3" }, expect: "any-2xx" },
  { name: "composer-cancel-project", category: "composer-render", body: { sceneId: "00000000-0000-0000-0000-000000000001", dryRun: true }, expect: "any-2xx" },
  { name: "composer-export-bundle", category: "composer-render", body: { sceneId: "00000000-0000-0000-0000-000000000001", dryRun: true }, expect: "any-2xx" },
  { name: "composer-export-edl", category: "composer-render", body: { sceneId: "00000000-0000-0000-0000-000000000001", dryRun: true }, expect: "any-2xx" },
  { name: "composer-export-fcpxml", category: "composer-render", body: { sceneId: "00000000-0000-0000-0000-000000000001", dryRun: true }, expect: "any-2xx" },
  { name: "composer-import-fcpxml", category: "composer-render", body: { sceneId: "00000000-0000-0000-0000-000000000001", dryRun: true }, expect: "any-2xx" },
  { name: "composer-undo", category: "composer-render", body: { sceneId: "00000000-0000-0000-0000-000000000001", dryRun: true }, expect: "any-2xx" },
  { name: "debug-render-status", category: "composer-render", body: { sceneId: "00000000-0000-0000-0000-000000000001", dryRun: true }, expect: "any-2xx" },
  { name: "estimate-render-cost", category: "composer-render", body: { sceneId: "00000000-0000-0000-0000-000000000001", dryRun: true }, expect: "any-2xx" },
  { name: "invite-composer-collaborator", category: "composer-render", body: { sceneId: "00000000-0000-0000-0000-000000000001", dryRun: true }, expect: "any-2xx" },
  { name: "recover-stuck-composer-clip", category: "composer-render", body: { sceneId: "00000000-0000-0000-0000-000000000001", dryRun: true }, expect: "any-2xx" },
  { name: "render-directors-cut", category: "composer-render", body: { sceneId: "00000000-0000-0000-0000-000000000001", dryRun: true }, expect: "any-2xx" },
  { name: "render-long-form-video", category: "composer-render", body: { sceneId: "00000000-0000-0000-0000-000000000001", dryRun: true }, expect: "any-2xx" },
  { name: "render-multi-format", category: "composer-render", body: { sceneId: "00000000-0000-0000-0000-000000000001", dryRun: true }, expect: "any-2xx" },
  { name: "render-multi-format-batch", category: "composer-render", body: { sceneId: "00000000-0000-0000-0000-000000000001", dryRun: true }, expect: "any-2xx" },
  { name: "render-queue-add", category: "composer-render", body: { sceneId: "00000000-0000-0000-0000-000000000001", dryRun: true }, expect: "any-2xx" },
  { name: "render-queue-cancel", category: "composer-render", body: { sceneId: "00000000-0000-0000-0000-000000000001", dryRun: true }, expect: "any-2xx" },
  { name: "render-queue-manager", category: "composer-render", body: { sceneId: "00000000-0000-0000-0000-000000000001", dryRun: true }, expect: "any-2xx" },
  { name: "render-universal-video", category: "composer-render", body: { sceneId: "00000000-0000-0000-0000-000000000001", dryRun: true }, expect: "any-2xx" },
  { name: "render-with-remotion", category: "composer-render", body: { sceneId: "00000000-0000-0000-0000-000000000001", dryRun: true }, expect: "any-2xx" },
  { name: "save-composer-scene-to-library", category: "composer-render", body: { sceneId: "00000000-0000-0000-0000-000000000001", dryRun: true }, expect: "any-2xx" },
  { name: "parse-briefing", category: "briefing-director", body: { briefing: "qa test brief" }, expect: "any-2xx" },
  { name: "analyze-scene-subject", category: "briefing-composer", body: { imageUrl: MOCK_IMAGE }, expect: "any-2xx" },
  { name: "analyze-script", category: "briefing-composer", body: { script: "qa" }, expect: "any-2xx" },
  { name: "analyze-script-for-video", category: "briefing-composer", body: { script: "qa" }, expect: "any-2xx" },
  { name: "analyze-style-reference", category: "briefing-composer", body: { imageUrl: MOCK_IMAGE }, expect: "any-2xx" },
  { name: "analyze-video-scenes", category: "briefing-composer", body: { videoUrl: "https://example.com/v.mp4" }, expect: "any-2xx" },
  { name: "briefing-deep-parse", category: "briefing-composer", body: { briefingText: "qa", language: "en" }, expect: "any-2xx" },
  { name: "compose-clip-webhook", category: "briefing-composer", body: { predictionId: "qa-mock" }, expect: "any-2xx" },
  { name: "compose-dialog-scene", category: "briefing-composer", body: { sceneId: MOCK_UUID }, expect: "any-2xx" },
  { name: "compose-dialog-segments", category: "briefing-composer", body: { sceneId: MOCK_UUID }, expect: "any-2xx" },
  { name: "compose-scene-variants", category: "briefing-composer", body: { sceneId: MOCK_UUID }, expect: "any-2xx" },
  { name: "compose-stitch-and-handoff", category: "briefing-composer", body: { projectId: MOCK_UUID }, expect: "any-2xx" },
  { name: "compose-video-assemble", category: "briefing-composer", body: { projectId: MOCK_UUID }, expect: "any-2xx" },
  { name: "compose-video-clips", category: "briefing-composer", body: { sceneId: MOCK_UUID }, expect: "any-2xx" },
  { name: "compose-video-storyboard", category: "briefing-composer", body: { briefing: "qa" }, expect: "any-2xx" },
  {
    name: "extract-subtitle-keywords",
    category: "briefing-composer",
    body: { subtitles: [{ id: "1", text: "this is a test line" }], language: "en" },
    expect: "any-2xx",
  },
  { name: "generate-image-prompt",            category: "briefing-composer", body: { userText: "qa" }, expect: "any-2xx" },
  { name: "hybrid-extend-scene", category: "briefing-composer", body: { sceneId: MOCK_UUID }, expect: "any-2xx" },
  { name: "reset-lipsync-scene", category: "briefing-composer", body: { sceneId: MOCK_UUID }, expect: "any-2xx" },
  { name: "scene-director", category: "briefing-composer", body: { description: "qa", durationSec: 5 }, expect: "any-2xx" },
  { name: "director-cut-upscale", category: "image-providers", body: { prompt: "qa test image" }, expect: "any-2xx" },
  { name: "magic-edit-image", category: "image-providers", body: { prompt: "qa test image" }, expect: "any-2xx" },
  { name: "seed-wardrobe-catalog", category: "image-providers", body: { prompt: "qa test image" }, expect: "any-2xx" },
  { name: "structured-prompt-compose", category: "image-providers", body: { prompt: "qa test image" }, expect: "any-2xx" },
  { name: "upscale-image", category: "image-providers", body: { prompt: "qa test image" }, expect: "any-2xx" },
  { name: "connect-instagram-performance", category: "social-meta", body: { dryRun: true }, expect: "any-2xx" },
  { name: "facebook-list-pages", category: "social-meta", body: { dryRun: true }, expect: "any-2xx" },
  { name: "facebook-oauth-start", category: "social-meta", body: { dryRun: true }, expect: "any-2xx" },
  { name: "facebook-page-sync", category: "social-meta", body: { dryRun: true }, expect: "any-2xx" },
  { name: "facebook-select-page", category: "social-meta", body: { dryRun: true }, expect: "any-2xx" },
  { name: "instagram-oauth-revoke", category: "social-meta", body: { dryRun: true }, expect: "any-2xx" },
  { name: "instagram-oauth-start", category: "social-meta", body: { dryRun: true }, expect: "any-2xx" },
  { name: "instagram-token-backups", category: "social-meta", body: { dryRun: true }, expect: "any-2xx" },
  { name: "instagram-token-debug", category: "social-meta", body: { dryRun: true }, expect: "any-2xx" },
  { name: "instagram-token-renew", category: "social-meta", body: { dryRun: true }, expect: "any-2xx" },
  { name: "instagram-token-update", category: "social-meta", body: { dryRun: true }, expect: "any-2xx" },
  { name: "tiktok-disconnect", category: "social-tiktok-twitch", body: { dryRun: true }, expect: "any-2xx" },
  { name: "tiktok-oauth-start", category: "social-tiktok-twitch", body: { dryRun: true }, expect: "any-2xx" },
  { name: "twitch-bits", category: "social-tiktok-twitch", body: { dryRun: true }, expect: "any-2xx" },
  { name: "twitch-channel-update", category: "social-tiktok-twitch", body: { dryRun: true }, expect: "any-2xx" },
  { name: "twitch-chatters", category: "social-tiktok-twitch", body: { dryRun: true }, expect: "any-2xx" },
  { name: "twitch-clip-create", category: "social-tiktok-twitch", body: { dryRun: true }, expect: "any-2xx" },
  { name: "twitch-clips", category: "social-tiktok-twitch", body: { dryRun: true }, expect: "any-2xx" },
  { name: "twitch-followers", category: "social-tiktok-twitch", body: { dryRun: true }, expect: "any-2xx" },
  { name: "twitch-games-search", category: "social-tiktok-twitch", body: { dryRun: true }, expect: "any-2xx" },
  { name: "twitch-hype-train", category: "social-tiktok-twitch", body: { dryRun: true }, expect: "any-2xx" },
  { name: "twitch-polls", category: "social-tiktok-twitch", body: { dryRun: true }, expect: "any-2xx" },
  { name: "twitch-predictions", category: "social-tiktok-twitch", body: { dryRun: true }, expect: "any-2xx" },
  { name: "twitch-rewards", category: "social-tiktok-twitch", body: { dryRun: true }, expect: "any-2xx" },
  { name: "twitch-schedule", category: "social-tiktok-twitch", body: { dryRun: true }, expect: "any-2xx" },
  { name: "twitch-send-chat", category: "social-tiktok-twitch", body: { dryRun: true }, expect: "any-2xx" },
  { name: "twitch-stream", category: "social-tiktok-twitch", body: { dryRun: true }, expect: "any-2xx" },
  { name: "twitch-user", category: "social-tiktok-twitch", body: { dryRun: true }, expect: "any-2xx" },
  { name: "calendar-google-oauth", category: "social-google", body: { dryRun: true }, expect: "any-2xx" },
  { name: "calendar-publish-dispatcher", category: "social-other", body: { dryRun: true }, expect: "any-2xx" },
  { name: "linkedin-disconnect", category: "social-other", body: { dryRun: true }, expect: "any-2xx" },
  { name: "linkedin-oauth-callback", category: "social-other", body: { dryRun: true }, expect: "any-2xx" },
  { name: "linkedin-oauth-start", category: "social-other", body: { dryRun: true }, expect: "any-2xx" },
  { name: "notify-expired-social-tokens", category: "social-other", body: { dryRun: true }, expect: "any-2xx" },
  { name: "x-disconnect", category: "social-other", body: { dryRun: true }, expect: "any-2xx" },
  { name: "x-oauth-callback", category: "social-other", body: { dryRun: true }, expect: "any-2xx" },
  { name: "x-oauth-start", category: "social-other", body: { dryRun: true }, expect: "any-2xx" },
  { name: "get-comments",                 category: "social-publishing", body: { postId: "qa-mock" }, expect: "any-2xx" },
  { name: "instagram-graph-sync", category: "social-publishing", body: {}, expect: "any-2xx" },
  { name: "instagram-publish", category: "social-publishing", body: { caption: "qa" }, expect: "any-2xx" },
  { name: "instagram-token-test", category: "social-publishing", body: {}, expect: "any-2xx" },
  { name: "linkedin-metrics", category: "social-publishing", body: {}, expect: "any-2xx" },
  { name: "linkedin-post", category: "social-publishing", body: { text: "qa" }, expect: "any-2xx" },
  { name: "publish-post", category: "social-publishing", body: { platform: "tiktok", postText: "qa" }, expect: "any-2xx" },
  { name: "publish-to-instagram", category: "social-publishing", body: { caption: "qa" }, expect: "any-2xx" },
  { name: "publish-to-linkedin", category: "social-publishing", body: { text: "qa" }, expect: "any-2xx" },
  { name: "publish-to-tiktok", category: "social-publishing", body: { caption: "qa", videoUrl: "https://example.com/v.mp4" }, expect: "any-2xx" },
  { name: "publish-to-youtube", category: "social-publishing", body: { title: "qa", videoUrl: "https://example.com/v.mp4" }, expect: "any-2xx" },
  { name: "schedule-post-with-ab", category: "social-publishing", body: { postId: "qa-mock" }, expect: "any-2xx" },
  { name: "social-health", category: "social-publishing", body: {}, expect: "any-2xx" },
  { name: "tiktok-health", category: "social-publishing", body: {}, expect: "any-2xx" },
  { name: "tiktok-sync", category: "social-publishing", body: {}, expect: "any-2xx" },
  { name: "tiktok-upload", category: "social-publishing", body: { videoUrl: "https://example.com/v.mp4" }, expect: "any-2xx" },
  { name: "x-publish", category: "social-publishing", body: { text: "qa" }, expect: "any-2xx" },
  { name: "x-refresh", category: "social-publishing", body: {}, expect: "any-2xx" },
  { name: "x-refresh-token", category: "social-publishing", body: {}, expect: "any-2xx" },
  { name: "youtube-live", category: "social-publishing", body: {}, expect: "any-2xx" },
  { name: "calendar-approve-stage", category: "calendar-planning", body: {}, expect: "any-2xx" },
  { name: "calendar-autoschedule", category: "calendar-planning", body: {}, expect: "any-2xx" },
  { name: "calendar-bulk-schedule", category: "calendar-planning", body: {}, expect: "any-2xx" },
  { name: "calendar-campaign-generate", category: "calendar-planning", body: {}, expect: "any-2xx" },
  { name: "calendar-capacity-check", category: "calendar-planning", body: {}, expect: "any-2xx" },
  { name: "calendar-create-approval-link", category: "calendar-planning", body: {}, expect: "any-2xx" },
  { name: "calendar-create-recurring-rule", category: "calendar-planning", body: {}, expect: "any-2xx" },
  { name: "calendar-export", category: "calendar-planning", body: {}, expect: "any-2xx" },
  { name: "calendar-export-pdf", category: "calendar-planning", body: {}, expect: "any-2xx" },
  { name: "calendar-holiday-suggestions", category: "calendar-planning", body: {}, expect: "any-2xx" },
  { name: "calendar-process-recurring-events", category: "calendar-planning", body: {}, expect: "any-2xx" },
  { name: "calendar-reject-approval", category: "calendar-planning", body: {}, expect: "any-2xx" },
  { name: "calendar-request-approval", category: "calendar-planning", body: {}, expect: "any-2xx" },
  { name: "calendar-reschedule", category: "calendar-planning", body: {}, expect: "any-2xx" },
  { name: "calendar-send-notification", category: "calendar-planning", body: {}, expect: "any-2xx" },
  { name: "calendar-sync-google", category: "calendar-planning", body: {}, expect: "any-2xx" },
  { name: "calendar-timeline-slots", category: "calendar-planning", body: {}, expect: "any-2xx" },
  { name: "calendar-validate", category: "calendar-planning", body: {}, expect: "any-2xx" },
  { name: "campaign-to-calendar", category: "calendar-planning", body: {}, expect: "any-2xx" },
  { name: "planner-apply-recommendations", category: "planner-strategy", body: {}, expect: "any-2xx" },
  { name: "planner-approve", category: "planner-strategy", body: {}, expect: "any-2xx" },
  { name: "planner-conflicts", category: "planner-strategy", body: {}, expect: "any-2xx" },
  { name: "planner-list", category: "planner-strategy", body: {}, expect: "any-2xx" },
  { name: "planner-to-calendar", category: "planner-strategy", body: {}, expect: "any-2xx" },
  { name: "planner-upsert-blocks", category: "planner-strategy", body: {}, expect: "any-2xx" },
  { name: "planner-upsert-weekplan", category: "planner-strategy", body: {}, expect: "any-2xx" },
  { name: "tick-strategy-posts", category: "planner-strategy", body: {}, expect: "any-2xx" },
  { name: "generate-ad-script", category: "ai-text-generation", body: {}, expect: "any-2xx" },
  { name: "auto-director-compose", category: "automation-jobs-1", body: { briefing: "qa" }, expect: "any-2xx" },
  { name: "auto-generate-universal-video", category: "automation-jobs-1", body: { topic: "qa" }, expect: "any-2xx" },
  { name: "batch-create-videos", category: "automation-jobs-1", body: { briefs: [] }, expect: "any-2xx" },
  { name: "create-video-batch", category: "automation-jobs-1", body: {}, expect: "any-2xx" },
  { name: "create-video-batch-v2", category: "automation-jobs-1", body: {}, expect: "any-2xx" },
  { name: "create-video-from-template", category: "automation-jobs-1", body: {}, expect: "any-2xx" },
  { name: "generate-bio", category: "automation-jobs-1", body: {}, expect: "any-2xx" },
  { name: "generate-campaign", category: "automation-jobs-1", body: {}, expect: "any-2xx" },
  { name: "generate-caption", category: "automation-jobs-1", body: {}, expect: "any-2xx" },
  { name: "generate-carousel", category: "automation-jobs-1", body: {}, expect: "any-2xx" },
  { name: "generate-first-video-prompts", category: "automation-jobs-1", body: {}, expect: "any-2xx" },
  { name: "generate-followup-question", category: "automation-jobs-1", body: {}, expect: "any-2xx" },
  { name: "generate-long-form-script", category: "automation-jobs-1", body: {}, expect: "any-2xx" },
  { name: "generate-optimized-prompt", category: "automation-jobs-1", body: {}, expect: "any-2xx" },
  { name: "generate-post", category: "automation-jobs-1", body: {}, expect: "any-2xx" },
  { name: "generate-post-caption", category: "automation-jobs-1", body: {}, expect: "any-2xx" },
  { name: "generate-post-v2", category: "automation-jobs-1", body: {}, expect: "any-2xx" },
  { name: "generate-posting-slots", category: "automation-jobs-1", body: {}, expect: "any-2xx" },
  { name: "generate-reply-suggestions", category: "automation-jobs-1", body: {}, expect: "any-2xx" },
  { name: "generate-scene-dialog", category: "automation-jobs-1", body: {}, expect: "any-2xx" },
  { name: "generate-share-link", category: "automation-jobs-1", body: {}, expect: "any-2xx" },
  { name: "generate-starter-plan", category: "automation-jobs-1", body: {}, expect: "any-2xx" },
  { name: "generate-subtitle-script", category: "automation-jobs-1", body: {}, expect: "any-2xx" },
  { name: "generate-subtitles", category: "automation-jobs-1", body: {}, expect: "any-2xx" },
  { name: "generate-universal-script", category: "automation-jobs-1", body: {}, expect: "any-2xx" },
  { name: "generate-video-script", category: "automation-jobs-2", body: {}, expect: "any-2xx" },
  { name: "generate-week-strategy", category: "automation-jobs-2", body: {}, expect: "any-2xx" },
  { name: "process-queue-delayed", category: "automation-jobs-2", body: {}, expect: "any-2xx" },
  { name: "process-verify-reminders", category: "automation-jobs-2", body: {}, expect: "any-2xx" },
  { name: "process-video-render", category: "automation-jobs-2", body: {}, expect: "any-2xx" },
  { name: "submit-character-to-marketplace", category: "automation-jobs-2", body: {}, expect: "any-2xx" },
  { name: "submit-template-rating", category: "automation-jobs-2", body: {}, expect: "any-2xx" },
  { name: "submit-template-to-marketplace", category: "automation-jobs-2", body: {}, expect: "any-2xx" },
  { name: "auth-email-hook", category: "notifications-email", body: {}, expect: "any-2xx" },
  { name: "email-unsubscribe", category: "notifications-email", body: {}, expect: "any-2xx" },
  { name: "process-activation-emails", category: "notifications-email", body: {}, expect: "any-2xx" },
  { name: "process-drip-emails", category: "notifications-email", body: {}, expect: "any-2xx" },
  { name: "process-push-reminders", category: "notifications-email", body: {}, expect: "any-2xx" },
  { name: "process-winback-emails", category: "notifications-email", body: {}, expect: "any-2xx" },
  { name: "send-email-campaign-test", category: "notifications-email", body: {}, expect: "any-2xx" },
  { name: "send-password-reset-email", category: "notifications-email", body: {}, expect: "any-2xx" },
  { name: "send-push-notification", category: "notifications-email", body: {}, expect: "any-2xx" },
  { name: "send-support-ticket", category: "notifications-email", body: {}, expect: "any-2xx" },
  { name: "triage-support-ticket", category: "notifications-email", body: {}, expect: "any-2xx" },
  { name: "notify-ticket-resolved", category: "notifications-email", body: {}, expect: "any-2xx" },

  { name: "send-verification-email", category: "notifications-email", body: {}, expect: "any-2xx" },
  { name: "update-email-preferences", category: "notifications-email", body: {}, expect: "any-2xx" },
  { name: "verify-email", category: "notifications-email", body: {}, expect: "any-2xx" },
  { name: "coach-chat", category: "community-coach", body: {}, expect: "any-2xx" },
  { name: "comments-summary", category: "community-coach", body: {}, expect: "any-2xx" },
  { name: "community-moderate", category: "community-coach", body: {}, expect: "any-2xx" },
  { name: "community-notify", category: "community-coach", body: {}, expect: "any-2xx" },
  { name: "community-spotlight-rotate", category: "community-coach", body: {}, expect: "any-2xx" },
  { name: "companion-diagnose", category: "community-coach", body: {}, expect: "any-2xx" },
  { name: "companion-speak", category: "community-coach", body: {}, expect: "any-2xx" },
  { name: "import-comments", category: "community-coach", body: {}, expect: "any-2xx" },
  { name: "ai-superuser-test-runner", category: "qa-testing", body: {}, expect: "any-2xx" },
  { name: "compare-lab-generate", category: "qa-testing", body: {}, expect: "any-2xx" },
  { name: "compare-lab-judge", category: "qa-testing", body: {}, expect: "any-2xx" },
  { name: "consistency-watcher", category: "qa-testing", body: {}, expect: "any-2xx" },
  { name: "create-ab-test", category: "qa-testing", body: {}, expect: "any-2xx" },
  { name: "create-test-jobs", category: "qa-testing", body: {}, expect: "any-2xx" },
  { name: "daily-smoke-test", category: "qa-testing", body: {}, expect: "any-2xx" },
  { name: "qa-agent-execute-mission", category: "qa-testing", body: {}, expect: "any-2xx" },
  { name: "qa-agent-orchestrator", category: "qa-testing", body: {}, expect: "any-2xx" },
  { name: "qa-agent-setup-test-user", category: "qa-testing", body: {}, expect: "any-2xx" },
  { name: "qa-bug-harvester", category: "qa-testing", body: {}, expect: "any-2xx" },
  { name: "qa-deep-sweep-finalize-stale", category: "qa-testing", body: {}, expect: "any-2xx" },
  { name: "qa-gemini-mp4-url-probe", category: "qa-testing", body: {}, expect: "any-2xx" },
  { name: "qa-live-sweep", category: "qa-testing", body: {}, expect: "any-2xx" },
  { name: "qa-live-sweep-bootstrap", category: "qa-testing", body: {}, expect: "any-2xx" },
  { name: "qa-weekly-deep-sweep", category: "qa-testing", body: {}, expect: "any-2xx" },
  { name: "smoke-matrix-run", category: "qa-testing", body: {}, expect: "any-2xx" },
  { name: "accept-invitation", category: "utilities", body: {}, expect: "any-2xx" },
  { name: "add-collaborator", category: "utilities", body: {}, expect: "any-2xx" },
  { name: "cloud-storage-oauth", category: "utilities", body: {}, expect: "any-2xx" },
  { name: "cloud-storage-sync", category: "utilities", body: {}, expect: "any-2xx" },
  { name: "extract-asset-from-frame", category: "utilities", body: {}, expect: "any-2xx" },
  { name: "extract-character-identity", category: "utilities", body: {}, expect: "any-2xx" },
  { name: "extract-location-identity", category: "utilities", body: {}, expect: "any-2xx" },
  { name: "extract-video-frames", category: "utilities", body: {}, expect: "any-2xx" },
  { name: "extract-video-last-frame", category: "utilities", body: {}, expect: "any-2xx" },
  { name: "token-expiry-notifier", category: "utilities", body: {}, expect: "any-2xx" },
  { name: "token-status", category: "utilities", body: {}, expect: "any-2xx" },
  { name: "translate-to-english", category: "utilities", body: {}, expect: "any-2xx" },
  { name: "translate-video", category: "utilities", body: {}, expect: "any-2xx" },
  { name: "validate-frame-face", category: "utilities", body: {}, expect: "any-2xx" },
  { name: "validate-promo-code", category: "utilities", body: {}, expect: "any-2xx" },
  { name: "verify-license-certificate", category: "utilities", body: {}, expect: "any-2xx" },
  { name: "fetch-news-hub",               category: "data-fetch", body: { language: "en" }, expect: "any-2xx" },
  { name: "fetch-news-radar",             category: "data-fetch", body: { language: "en" }, expect: "any-2xx" },
  { name: "fetch-trends",                 category: "data-fetch", body: { language: "en" }, expect: "any-2xx" },
  { name: "get-video-templates",          category: "data-fetch", body: {}, expect: "any-2xx" },
  { name: "invoke-remotion-render", category: "data-fetch", body: {}, expect: "any-2xx" },
  { name: "media-import", category: "data-fetch", body: {}, expect: "any-2xx" },
  { name: "media-upload-complete", category: "data-fetch", body: {}, expect: "any-2xx" },
  { name: "motion-studio-director", category: "data-fetch", body: {}, expect: "any-2xx" },
  { name: "motion-studio-superuser", category: "data-fetch", body: {}, expect: "any-2xx" },
  { name: "provider-quota-aggregator", category: "data-fetch", body: {}, expect: "any-2xx" },
  { name: "provider-quota-alerter", category: "data-fetch", body: {}, expect: "any-2xx" },
  { name: "provider-quota-backfill", category: "data-fetch", body: {}, expect: "any-2xx" },
  { name: "remotion-webhook", category: "data-fetch", body: {}, expect: "any-2xx" },
  { name: "review-marketplace-character", category: "data-fetch", body: {}, expect: "any-2xx" },
  { name: "review-marketplace-template", category: "data-fetch", body: {}, expect: "any-2xx" },
  { name: "search-stock-images", category: "data-fetch", body: {}, expect: "any-2xx" },
  {
    name: "search-stock-videos",
    category: "data-fetch",
    body: { query: "ocean", page: 1, perPage: 4 },
    expect: "any-2xx",
  },
  { name: "search-trend-articles", category: "data-fetch", body: {}, expect: "any-2xx" },
  { name: "seed-default-profiles", category: "data-fetch", body: {}, expect: "any-2xx" },
  { name: "seed-world-catalog", category: "data-fetch", body: {}, expect: "any-2xx" },
  { name: "text-studio-chat", category: "data-fetch", body: {}, expect: "any-2xx" },
  { name: "text-studio-compare", category: "data-fetch", body: {}, expect: "any-2xx" },
  { name: "update-workspace-seats", category: "data-fetch", body: {}, expect: "any-2xx" },
  { name: "admin-stripe-inspect", category: "billing-credits", body: { dryRun: true }, expect: "any-2xx" },
  { name: "admin-stripe-setup-pricing-v2", category: "billing-credits", body: { dryRun: true }, expect: "any-2xx" },
  { name: "ai-video-purchase-credits", category: "billing-credits", body: { dryRun: true }, expect: "any-2xx" },
  { name: "ai-video-verify-purchase", category: "billing-credits", body: { dryRun: true }, expect: "any-2xx" },
  { name: "check-subscription",           category: "billing-credits", body: {}, expect: "any-2xx" },
  { name: "create-checkout", category: "billing-credits", body: {}, expect: "any-2xx" },
  { name: "create-enterprise-checkout", category: "billing-credits", body: {}, expect: "any-2xx" },
  { name: "credit-refund", category: "billing-credits", body: { dryRun: true }, expect: "any-2xx" },
  { name: "get-invoices",                 category: "billing-credits", body: {}, expect: "any-2xx" },
  { name: "purchase-marketplace-character", category: "billing-credits", body: { dryRun: true }, expect: "any-2xx" },
  { name: "purchase-marketplace-template", category: "billing-credits", body: { dryRun: true }, expect: "any-2xx" },
  { name: "stripe-webhook", category: "billing-credits", body: { dryRun: true }, expect: "any-2xx" },
  { name: "admin-cost-snapshot", category: "analytics-reports", body: {}, expect: "any-2xx" },
  { name: "admin-stats", category: "analytics-reports", body: {}, expect: "any-2xx" },
  { name: "analyze-ad-campaign-performance", category: "analytics-reports", body: { campaignId: "qa-mock" }, expect: "any-2xx" },
  { name: "analyze-comments", category: "analytics-reports", body: { postId: "qa-mock" }, expect: "any-2xx" },
  { name: "analyze-goal-progress", category: "analytics-reports", body: {}, expect: "any-2xx" },
  { name: "analyze-hashtags", category: "analytics-reports", body: { text: "qa" }, expect: "any-2xx" },
  { name: "analyze-performance", category: "analytics-reports", body: { range: "7d" }, expect: "any-2xx" },
  { name: "analyze-performance-strategy", category: "analytics-reports", body: { range: "7d" }, expect: "any-2xx" },
  { name: "analyze-post-optimization", category: "analytics-reports", body: { postText: "qa" }, expect: "any-2xx" },
  { name: "analyze-posting-times", category: "analytics-reports", body: { platform: "tiktok" }, expect: "any-2xx" },
  { name: "analyze-trend", category: "analytics-reports", body: { trend: "qa" }, expect: "any-2xx" },
  { name: "apply-optimization", category: "analytics-reports", body: { optimizationId: "qa-mock" }, expect: "any-2xx" },
  { name: "calculate-cost-savings", category: "analytics-reports", body: {}, expect: "any-2xx" },
  { name: "calculate-storage-usage", category: "analytics-reports", body: { dryRun: true }, expect: "any-2xx" },
  { name: "fetch-analytics",              category: "analytics-reports", body: {}, expect: "any-2xx" },
  { name: "generate-usage-report", category: "analytics-reports", body: { dryRun: true }, expect: "any-2xx" },
  { name: "get-ab-test-results",          category: "analytics-reports", body: {}, expect: "any-2xx" },
  { name: "posthog-analytics", category: "analytics-reports", body: { dryRun: true }, expect: "any-2xx" },
  { name: "report-marketplace-character", category: "analytics-reports", body: { dryRun: true }, expect: "any-2xx" },
  { name: "save-post-metrics", category: "analytics-reports", body: { dryRun: true }, expect: "any-2xx" },
  { name: "test-posthog-event", category: "analytics-reports", body: { dryRun: true }, expect: "any-2xx" },
  { name: "track-credit-usage", category: "analytics-reports", body: { dryRun: true }, expect: "any-2xx" },
  { name: "track-user-behavior", category: "analytics-reports", body: { dryRun: true }, expect: "any-2xx" },
  { name: "ai-companion", category: "misc-1", body: { message: "qa" }, expect: "any-2xx" },
  { name: "analyze-superuser-anomalies", category: "misc-1", body: {}, expect: "any-2xx" },
  { name: "autopilot-generate-video", category: "misc-1", body: {}, expect: "any-2xx" },
  { name: "campaign-to-planner", category: "misc-1", body: {}, expect: "any-2xx" },
  { name: "compress-video", category: "misc-1", body: {}, expect: "any-2xx" },
  { name: "credit-commit", category: "misc-1", body: {}, expect: "any-2xx" },
  { name: "credit-preflight", category: "misc-1", body: {}, expect: "any-2xx" },
  { name: "credit-reserve", category: "misc-1", body: {}, expect: "any-2xx" },
  { name: "customer-portal", category: "misc-1", body: {}, expect: "any-2xx" },
  { name: "dashboard-calendar-summary", category: "misc-1", body: {}, expect: "any-2xx" },
  { name: "dashboard-goals-summary", category: "misc-1", body: {}, expect: "any-2xx" },
  { name: "detect-scene-drift", category: "misc-1", body: {}, expect: "any-2xx" },
  { name: "director-cut-auto-cut", category: "misc-1", body: {}, expect: "any-2xx" },
  { name: "director-cut-auto-enhance", category: "misc-1", body: {}, expect: "any-2xx" },
  { name: "director-cut-beat-sync", category: "misc-1", body: {}, expect: "any-2xx" },
  { name: "director-cut-burned-subtitles-webhook", category: "misc-1", body: {}, expect: "any-2xx" },
  { name: "director-cut-chroma-key", category: "misc-1", body: {}, expect: "any-2xx" },
  { name: "director-cut-copilot", category: "misc-1", body: {}, expect: "any-2xx" },
  { name: "director-cut-detect-subtitle-band", category: "misc-1", body: {}, expect: "any-2xx" },
  { name: "director-cut-interpolation", category: "misc-1", body: {}, expect: "any-2xx" },
  { name: "director-cut-object-removal", category: "misc-1", body: {}, expect: "any-2xx" },
  { name: "director-cut-remove-burned-subtitles", category: "misc-1", body: {}, expect: "any-2xx" },
  { name: "director-cut-restoration", category: "misc-1", body: {}, expect: "any-2xx" },
  { name: "director-cut-smart-crop", category: "misc-1", body: {}, expect: "any-2xx" },
  { name: "director-cut-style-transfer", category: "misc-1", body: {}, expect: "any-2xx" },
  { name: "director-cut-transitions", category: "misc-2", body: {}, expect: "any-2xx" },
  { name: "discord-webhook", category: "misc-2", body: {}, expect: "any-2xx" },
  { name: "evaluate-creator-level", category: "misc-2", body: {}, expect: "any-2xx" },
  { name: "export-post-bundle", category: "misc-2", body: {}, expect: "any-2xx" },
  { name: "grant-welcome-bonus", category: "misc-2", body: {}, expect: "any-2xx" },
  { name: "identify-best-content", category: "misc-2", body: {}, expect: "any-2xx" },
  { name: "ingest-e2e-results", category: "misc-2", body: {}, expect: "any-2xx" },
  { name: "issue-license-certificate", category: "misc-2", body: {}, expect: "any-2xx" },
  { name: "job-status", category: "misc-2", body: {}, expect: "any-2xx" },
  { name: "lambda-circuit-breaker", category: "misc-2", body: {}, expect: "any-2xx" },
  { name: "oauth-callback", category: "misc-2", body: {}, expect: "any-2xx" },
  { name: "optimize-video-prompt", category: "misc-2", body: {}, expect: "any-2xx" },
  { name: "poster-dispatcher", category: "misc-2", body: {}, expect: "any-2xx" },
  { name: "posting-times-api", category: "misc-2", body: {}, expect: "any-2xx" },
  { name: "proxy-video-bytes", category: "misc-2", body: {}, expect: "any-2xx" },
  { name: "publish", category: "misc-2", body: {}, expect: "any-2xx" },
  { name: "refresh-streak-freeze-tokens", category: "misc-2", body: {}, expect: "any-2xx" },
  { name: "replicate-webhook", category: "misc-2", body: {}, expect: "any-2xx" },
  { name: "resend-webhook", category: "misc-2", body: {}, expect: "any-2xx" },
  { name: "reset-monthly-credits", category: "misc-2", body: {}, expect: "any-2xx" },
  { name: "rewrite-caption", category: "misc-2", body: {}, expect: "any-2xx" },
  { name: "save-ai-video-to-library", category: "misc-2", body: {}, expect: "any-2xx" },
  { name: "select-optimal-engine", category: "misc-2", body: {}, expect: "any-2xx" },
  { name: "sync-posts-history", category: "misc-2", body: {}, expect: "any-2xx" },
  { name: "takedown-marketplace-character", category: "misc-2", body: {}, expect: "any-2xx" },
  { name: "template-to-planner", category: "misc-3", body: {}, expect: "any-2xx" },
  { name: "terminate-autopilot-abuse", category: "misc-3", body: {}, expect: "any-2xx" },
  { name: "transform-media", category: "misc-3", body: {}, expect: "any-2xx" },
  { name: "universal-video-consultant", category: "misc-3", body: {}, expect: "any-2xx" },
  { name: "upgrade-to-enterprise", category: "misc-3", body: {}, expect: "any-2xx" },
  { name: "preview-voice-hume", category: "audio-music-sfx-2", body: { voiceId: "qa", text: "hi" }, expect: "any-2xx" },
  { name: "proxy-audio", category: "audio-music-sfx-2", body: { url: MOCK_AUDIO }, expect: "any-2xx" },
  { name: "render-sync-segments-audio-mux", category: "audio-music-sfx-2", body: { projectId: MOCK_UUID }, expect: "any-2xx" },
  {
    name: "search-sfx-library",
    category: "audio-music-sfx-2",
    body: { query: "whoosh", page: 1, perPage: 4 },
    expect: "any-2xx",
  },
  {
    name: "search-stock-music",
    category: "audio-music-sfx-2",
    body: { query: "lofi", page: 1, perPage: 4 },
    expect: "any-2xx",
  },
  { name: "search-stock-sfx", category: "audio-music-sfx-2", body: { query: "boom", page: 1, perPage: 4 }, expect: "any-2xx" },
  { name: "seed-background-music", category: "audio-music-sfx-2", body: {}, expect: "any-2xx" },
  { name: "separate-audio-stems", category: "audio-music-sfx-2", body: { audioUrl: MOCK_AUDIO }, expect: "any-2xx" },
  { name: "suggest-video-music", category: "audio-music-sfx-2", body: { videoTopic: "qa" }, expect: "any-2xx" },
  { name: "transcribe-audio", category: "audio-music-sfx-2", body: { audioUrl: MOCK_AUDIO }, expect: "any-2xx" },
  { name: "translate-and-voiceover", category: "audio-music-sfx-2", body: { text: "qa", targetLang: "de" }, expect: "any-2xx" },
  { name: "upload-music-to-storage", category: "audio-music-sfx-2", body: { audioUrl: MOCK_AUDIO, title: "qa" }, expect: "any-2xx" },
  { name: "validate-music-track", category: "audio-music-sfx-2", body: { audioUrl: MOCK_AUDIO }, expect: "any-2xx" },
  { name: "check-render-status",          category: "admin-cron-2", body: { renderId: "qa-mock" }, expect: "any-2xx" },
  { name: "check-scheduled-publications", category: "admin-cron-2", body: {}, expect: "any-2xx" },
  { name: "check-streak-breaks",          category: "admin-cron-2", body: {}, expect: "any-2xx" },
  { name: "check-trial-status",           category: "admin-cron-2", body: {}, expect: "any-2xx" },
  { name: "check-video-status",           category: "admin-cron-2", body: { videoId: "qa-mock" }, expect: "any-2xx" },
  { name: "cleanup-old-videos", category: "admin-cron-2", body: { dryRun: true }, expect: "any-2xx" },
  { name: "cleanup-storage", category: "admin-cron-2", body: { dryRun: true }, expect: "any-2xx" },
  { name: "edge-function-warmer", category: "admin-cron-2", body: { dryRun: true }, expect: "any-2xx" },
  { name: "health-alerter",               category: "admin-cron-2", body: {}, expect: "any-2xx" },
  { name: "health-check",                 category: "admin-cron-2", body: {}, expect: "any-2xx" },
  { name: "health-ig",                    category: "admin-cron-2", body: {}, expect: "any-2xx" },
  { name: "health-li",                    category: "admin-cron-2", body: {}, expect: "any-2xx" },
  { name: "health-tt",                    category: "admin-cron-2", body: {}, expect: "any-2xx" },
  { name: "health-x",                     category: "admin-cron-2", body: {}, expect: "any-2xx" },
  { name: "health-yt",                    category: "admin-cron-2", body: {}, expect: "any-2xx" },
  { name: "lambda-health-monitor", category: "admin-cron-2", body: { dryRun: true }, expect: "any-2xx" },
  { name: "lambda-health-stats", category: "admin-cron-2", body: { dryRun: true }, expect: "any-2xx" },
  { name: "monitoring-alerts", category: "admin-cron-2", body: { dryRun: true }, expect: "any-2xx" },
  {
    name: "public-status",
    category: "admin-cron-2",
    body: {},
    expect: "any-2xx",
  },
  {
    name: "qa-watchdog",
    category: "admin-cron-2",
    body: { dryRun: true },
    expect: "any-2xx",
  },
  { name: "sentry-issues", category: "admin-cron-2", body: { dryRun: true }, expect: "any-2xx" },
  { name: "storage-bucket-health", category: "admin-cron-2", body: { dryRun: true }, expect: "any-2xx" },
  { name: "sync-metrics-cron", category: "admin-cron-2", body: { dryRun: true }, expect: "any-2xx" },
  {
    name: "synthetic-probe",
    category: "admin-cron-2",
    body: { dryRun: true },
    expect: "any-2xx",
  },
  { name: "weekly-health-report", category: "admin-cron-2", body: { dryRun: true }, expect: "any-2xx" },
  { name: "admin-delete-user", category: "admin-cron-1", body: { dryRun: true }, expect: "any-2xx" },
  { name: "admin-suppression-manage", category: "admin-cron-1", body: { dryRun: true }, expect: "any-2xx" },
  { name: "ai-queue-worker", category: "admin-cron-1", body: { dryRun: true }, expect: "any-2xx" },
  {
    name: "auto-refresh-meta-tokens",
    category: "admin-cron-1",
    body: { mode: "status" },
    expect: "any-2xx",
  },
  { name: "autopilot-daily-digest", category: "admin-cron-1", body: { dryRun: true }, expect: "any-2xx" },
  { name: "autopilot-emit-notification", category: "admin-cron-1", body: { event: "qa" }, expect: "any-2xx" },
  { name: "autopilot-generate-slot", category: "admin-cron-1", body: { slotId: "qa-mock" }, expect: "any-2xx" },
  { name: "autopilot-performance-analyze", category: "admin-cron-1", body: { dryRun: true }, expect: "any-2xx" },
  { name: "autopilot-plan-week", category: "admin-cron-1", body: { dryRun: true }, expect: "any-2xx" },
  { name: "autopilot-prompt-shield", category: "admin-cron-1", body: { prompt: "qa" }, expect: "any-2xx" },
  { name: "autopilot-publish-due", category: "admin-cron-1", body: { dryRun: true }, expect: "any-2xx" },
  { name: "autopilot-qa-gate", category: "admin-cron-1", body: { slotId: "qa-mock" }, expect: "any-2xx" },
  { name: "autopilot-safety-check", category: "admin-cron-1", body: { prompt: "qa" }, expect: "any-2xx" },
  { name: "autopilot-toggle", category: "admin-cron-1", body: { enabled: true }, expect: "any-2xx" },
  { name: "autopilot-video-poll", category: "admin-cron-1", body: { dryRun: true }, expect: "any-2xx" },
  { name: "autopilot-weekly-review", category: "admin-cron-1", body: { dryRun: true }, expect: "any-2xx" },
  { name: "cache-cleanup", category: "admin-cron-1", body: { dryRun: true }, expect: "any-2xx" },
  { name: "cache-invalidator", category: "admin-cron-1", body: { key: "qa" }, expect: "any-2xx" },
  { name: "cache-stats", category: "admin-cron-1", body: { dryRun: true }, expect: "any-2xx" },
  { name: "cache-stats-aggregator", category: "admin-cron-1", body: { dryRun: true }, expect: "any-2xx" },
  { name: "cache-warming", category: "admin-cron-1", body: { dryRun: true }, expect: "any-2xx" },
  { name: "check-calendar-deadlines",     category: "admin-cron-1", body: {}, expect: "any-2xx" },
  { name: "check-content-video-status",   category: "admin-cron-1", body: { videoId: "qa-mock" }, expect: "any-2xx" },
  { name: "check-remotion-progress",      category: "admin-cron-1", body: { renderId: "qa-mock" }, expect: "any-2xx" },
  { name: "check-render-cache",           category: "admin-cron-1", body: { cacheKey: "qa-mock" }, expect: "any-2xx" },
  { name: "analyze-brand-consistency", category: "picture-image-1", body: { imageUrl: MOCK_IMAGE }, expect: "any-2xx" },
  { name: "analyze-image-caption", category: "picture-image-1", body: { imageUrl: MOCK_IMAGE }, expect: "any-2xx" },
  {
    name: "analyze-image-v2",
    category: "picture-image-1",
    body: { imageUrl: MOCK_IMAGE },
    expect: "any-2xx",
  },
  {
    name: "analyze-logo",
    category: "picture-image-1",
    body: { imageUrl: MOCK_IMAGE },
    expect: "any-2xx",
  },
  { name: "clone-preset-avatar", category: "picture-image-1", body: { presetId: "qa-mock" }, expect: "any-2xx" },
  { name: "generate-avatar-portrait",         category: "picture-image-1", body: { prompt: "qa" }, expect: "any-2xx" },
  { name: "generate-avatar-poses",            category: "picture-image-1", body: { avatarId: "qa-mock" }, expect: "any-2xx" },
  { name: "generate-avatar-wardrobe",         category: "picture-image-1", body: { avatarId: "qa-mock" }, expect: "any-2xx" },
  { name: "generate-background-scenes",       category: "picture-image-1", body: { prompt: "qa" }, expect: "any-2xx" },
  { name: "generate-brand-asset",             category: "picture-image-1", body: { prompt: "qa", kind: "logo" }, expect: "any-2xx" },
  { name: "generate-brand-kit", category: "picture-image-1", body: { brandName: "qa" }, expect: "any-2xx" },
  { name: "generate-character-sheet",         category: "picture-image-1", body: { prompt: "qa" }, expect: "any-2xx" },
  { name: "generate-composer-image-scene",    category: "picture-image-1", body: { prompt: "qa" }, expect: "any-2xx" },
  {
    name: "generate-image-replicate",
    category: "picture-image-1",
    body: { prompt: "a cat", model: "flux-schnell" },
    expect: "ok-flag",
  },
  { name: "generate-location-props",          category: "picture-image-1", body: { locationId: "qa-mock" }, expect: "any-2xx" },
  { name: "generate-location-vibes",          category: "picture-image-1", body: { locationId: "qa-mock" }, expect: "any-2xx" },
  { name: "generate-premium-visual",          category: "picture-image-1", body: { prompt: "qa" }, expect: "any-2xx" },
  { name: "generate-scene-still",             category: "picture-image-1", body: { prompt: "qa" }, expect: "any-2xx" },
  { name: "generate-scene-visual",            category: "picture-image-1", body: { prompt: "qa" }, expect: "any-2xx" },
  { name: "generate-studio-image",            category: "picture-image-1", body: { prompt: "qa" }, expect: "any-2xx" },
  { name: "generate-thumbnail",               category: "picture-image-1", body: { prompt: "qa" }, expect: "any-2xx" },
  { name: "generate-video-thumbnail",         category: "picture-image-1", body: { prompt: "qa" }, expect: "any-2xx" },
  { name: "generate-wardrobe-perspectives",   category: "picture-image-1", body: { avatarId: "qa-mock" }, expect: "any-2xx" },
  { name: "generate-world-asset",             category: "picture-image-1", body: { prompt: "qa", kind: "prop" }, expect: "any-2xx" },
  { name: "repair-brand-character-urls", category: "picture-image-1", body: { dryRun: true }, expect: "any-2xx" },
  { name: "seed-preset-avatars", category: "picture-image-2", body: { dryRun: true }, expect: "any-2xx" },
  { name: "analyze-brand-voice", category: "audio-music-sfx-1", body: { audioUrl: MOCK_AUDIO }, expect: "any-2xx" },
  { name: "analyze-music-beats", category: "audio-music-sfx-1", body: { audioUrl: MOCK_AUDIO }, expect: "any-2xx" },
  { name: "analyze-music-bpm", category: "audio-music-sfx-1", body: { audioUrl: MOCK_AUDIO }, expect: "any-2xx" },
  { name: "audio-beat-detection", category: "audio-music-sfx-1", body: { audioUrl: MOCK_AUDIO }, expect: "any-2xx" },
  { name: "audio-studio-enhance", category: "audio-music-sfx-1", body: { audioUrl: MOCK_AUDIO }, expect: "any-2xx" },
  { name: "auto-match-music-to-video", category: "audio-music-sfx-1", body: { videoUrl: "https://example.com/v.mp4" }, expect: "any-2xx" },
  { name: "clone-voice", category: "audio-music-sfx-1", body: { name: "qa", audioUrl: MOCK_AUDIO }, expect: "any-2xx" },
  { name: "companion-transcribe", category: "audio-music-sfx-1", body: { audioUrl: MOCK_AUDIO }, expect: "any-2xx" },
  { name: "compose-twoshot-audio", category: "audio-music-sfx-1", body: { sceneId: MOCK_UUID }, expect: "any-2xx" },
  { name: "director-cut-audio-mixing", category: "audio-music-sfx-1", body: { projectId: MOCK_UUID }, expect: "any-2xx" },
  { name: "director-cut-sound-design", category: "audio-music-sfx-1", body: { projectId: MOCK_UUID }, expect: "any-2xx" },
  { name: "director-cut-voice-over", category: "audio-music-sfx-1", body: { projectId: MOCK_UUID, text: "qa" }, expect: "any-2xx" },
  { name: "generate-multi-speaker-vo", category: "audio-music-sfx-1", body: { sceneId: MOCK_UUID, lines: [] }, expect: "any-2xx" },
  { name: "generate-music-lyrics", category: "audio-music-sfx-1", body: { topic: "qa", duration: 30 }, expect: "any-2xx" },
  {
    name: "generate-music-track",
    category: "audio-music-sfx-1",
    body: { prompt: "lofi beat", duration: 5 },
    expect: "ok-flag",
  },
  {
    name: "generate-scene-sfx",
    category: "audio-music-sfx-1",
    body: { prompt: "door slam", duration: 2 },
    expect: "ok-flag",
  },
  {
    name: "generate-talking-head",
    category: "audio-music-sfx-1",
    body: { portraitUrl: MOCK_IMAGE, audioUrl: MOCK_AUDIO },
    expect: "ok-flag",
  },
  { name: "generate-video-voiceover", category: "audio-music-sfx-1", body: { text: "qa", voiceId: "qa" }, expect: "any-2xx" },
  { name: "generate-voiceover", category: "audio-music-sfx-1", body: { text: "qa", voiceId: "qa" }, expect: "any-2xx" },
  { name: "generate-voiceover-hume", category: "audio-music-sfx-1", body: { text: "qa", voiceId: "qa" }, expect: "any-2xx" },
  { name: "generate-voiceover-script", category: "audio-music-sfx-1", body: { topic: "qa", duration: 15 }, expect: "any-2xx" },
  { name: "list-voices", category: "audio-music-sfx-1", body: {}, expect: "any-2xx" },
  { name: "list-voices-hume", category: "audio-music-sfx-1", body: {}, expect: "any-2xx" },
  { name: "mux-audio-to-video", category: "audio-music-sfx-1", body: { videoUrl: "https://example.com/v.mp4", audioUrl: MOCK_AUDIO }, expect: "any-2xx" },
  { name: "preview-voice", category: "audio-music-sfx-1", body: { voiceId: "qa", text: "hi" }, expect: "any-2xx" },
];

/** Categories in display order for the Cockpit UI. */
export const SMOKE_CATEGORIES: Array<{ id: SmokeEntry["category"]; label: string }> = [
  { id: "ai-video-providers", label: "AI Video (Legacy)" },
  { id: "lipsync-dialog", label: "Lipsync & Dialog" },
  { id: "composer-render", label: "Composer & Render" },
  { id: "briefing-director", label: "Briefing & Director" },
  { id: "briefing-composer", label: "Briefing & Composer (Legacy)" },
  { id: "image-providers", label: "Image / Picture" },
  { id: "social-meta", label: "Social — Meta" },
  { id: "social-tiktok-twitch", label: "Social — TikTok/Twitch" },
  { id: "social-google", label: "Social — YouTube/Google" },
  { id: "social-other", label: "Social — Other" },
  { id: "social-publishing", label: "Social Publishing (Legacy)" },
  { id: "calendar-planning", label: "Calendar & Planning" },
  { id: "planner-strategy", label: "Planner & Strategy" },
  { id: "ai-text-generation", label: "AI Text Generation" },
  { id: "automation-jobs-1", label: "Automation & Jobs (1)" },
  { id: "automation-jobs-2", label: "Automation & Jobs (2)" },
  { id: "notifications-email", label: "Notifications & Email" },
  { id: "community-coach", label: "Community & Coach" },
  { id: "qa-testing", label: "QA & Testing" },
  { id: "utilities", label: "Utilities & Auth" },
  { id: "data-fetch", label: "Data Fetch & Lookups" },
  { id: "billing-credits", label: "Billing / Credits" },
  { id: "analytics-reports", label: "Analytics / Reports" },
  { id: "misc-1", label: "Misc (1)" },
  { id: "misc-2", label: "Misc (2)" },
  { id: "misc-3", label: "Misc (3)" },
  { id: "audio-music-sfx-2", label: "audio-music-sfx-2" },
  { id: "admin-cron-2", label: "admin-cron-2" },
  { id: "admin-cron-1", label: "admin-cron-1" },
  { id: "picture-image-1", label: "picture-image-1" },
  { id: "picture-image-2", label: "picture-image-2" },
  { id: "audio-music-sfx-1", label: "audio-music-sfx-1" },
];
