import { Helmet } from 'react-helmet-async';
import { Link } from 'react-router-dom';
import { ArrowLeft, ShieldCheck } from 'lucide-react';

export const CREATOR_TERMS_VERSION = 'v1-2026-04-29';

export default function MarketplaceCreatorTerms() {
  return (
    <>
      <Helmet>
        <title>Marketplace Creator Terms | AdTool</title>
        <meta name="description" content="Vertragsbedingungen für Creator, die Brand Characters im AdTool Marketplace anbieten." />
      </Helmet>
      <div className="container mx-auto max-w-3xl py-10 px-4">
        <Link to="/marketplace" className="inline-flex items-center gap-1 text-sm text-muted-foreground hover:text-foreground mb-6">
          <ArrowLeft className="h-4 w-4" /> Back to Marketplace
        </Link>
        <header className="flex items-start gap-3 mb-8">
          <ShieldCheck className="h-8 w-8 text-primary mt-1" />
          <div>
            <h1 className="text-3xl font-bold">Marketplace — Creator Terms</h1>
            <p className="text-sm text-muted-foreground mt-1">
              Version <code className="px-1.5 py-0.5 rounded bg-muted text-xs">{CREATOR_TERMS_VERSION}</code> · Effective 29 April 2026
            </p>
          </div>
        </header>

        <div className="prose prose-sm dark:prose-invert max-w-none space-y-6">
          <section>
            <h2>1. Scope</h2>
            <p>These terms apply to every user ("Creator") who submits a Brand Character / Avatar to the AdTool Marketplace ("Marketplace"). They supplement the general Terms of Service.</p>
          </section>

          <section>
            <h2>2. Origin Declaration (Mandatory)</h2>
            <p>The Creator must select exactly one origin category at submission and warrants its accuracy:</p>
            <ul>
              <li><strong>AI-Generated:</strong> The character was generated by an AI image model. The depicted person does not exist.</li>
              <li><strong>Licensed Real Person:</strong> The character depicts a real person. A valid model release covering commercial sub-licensing must be uploaded as PDF.</li>
              <li><strong>Self-Portrait:</strong> The Creator is the depicted person and consents to commercial use through the Marketplace.</li>
            </ul>
          </section>

          <section>
            <h2>3. Creator Warranties</h2>
            <p>By submitting a character the Creator warrants and represents that:</p>
            <ol>
              <li>They hold all rights, titles and licenses required to publish, sub-license and commercially distribute the character (image, voice, identity card, sample videos).</li>
              <li>If a real person is depicted, a written model release covering AI re-generation and commercial sub-licensing exists and remains valid for the duration of the listing.</li>
              <li>The character does not depict any public figure (politicians, celebrities, brand mascots, fictional characters owned by third parties) without explicit written authorisation from the rights holder.</li>
              <li>The character does not depict a minor (under 18) and is not designed to be perceived as a minor.</li>
              <li>The character does not infringe any trademark, copyright, personality, privacy, publicity or moral rights of any third party.</li>
              <li>The character does not contain illegal content, hate speech, defamatory material or sexually explicit content (unless explicitly tagged and reviewed under separate adult-content policy — currently disabled).</li>
            </ol>
          </section>

          <section>
            <h2>4. Revenue Share &amp; Payouts</h2>
            <p>Premium characters are sold against platform credits. Creator earns 70% of the credit price per sale, AdTool retains 30% as a platform fee. Earnings are added to the Creator's credit wallet immediately on sale and may be used for any platform-paid feature. Cash-out to fiat currency is not part of the current product (planned for a later phase).</p>
          </section>

          <section>
            <h2>5. Indemnification</h2>
            <p>The Creator shall fully indemnify, defend and hold harmless AdTool, its operators, employees and customers from and against any and all claims, damages, losses, liabilities, fines and expenses (including reasonable legal fees) arising out of or related to a breach of section 3, including but not limited to claims of personality rights infringement, copyright or trademark infringement, GDPR violations or unlawful deepfake creation.</p>
          </section>

          <section>
            <h2>6. Take-Down &amp; Sanctions</h2>
            <p>AdTool may, without prior notice and at its sole discretion: (a) place a character under investigation following a report; (b) unlist or permanently remove a character; (c) suspend or terminate the Creator's account; (d) reverse all earnings derived from the affected character; and (e) cooperate with law enforcement and rights holders. Permanent removal triggers automatic refund of all open buyer purchases at AdTool's expense; AdTool reserves the right to recover such refunds from the Creator in case of breach of section 3.</p>
          </section>

          <section>
            <h2>7. Audit Trail</h2>
            <p>All consents (sections 2 and 3) are recorded with timestamp, hashed IP address, user agent and legal version. The Creator acknowledges this audit trail may be used as evidence in legal proceedings.</p>
          </section>

          <section>
            <h2>8. Data Protection</h2>
            <p>Model release PDFs are stored in a private storage bucket accessible only to the Creator and AdTool administrators. PDFs are not used for AI training and are not shared with third parties except where required by law or by a documented rights-holder request.</p>
          </section>

          <section>
            <h2>9. Termination</h2>
            <p>The Creator may unlist any character at any time via their library. Already-sold buyer licenses remain valid (fair-use grandfathering); the Creator's earnings on these are not clawed back unless section 6 applies.</p>
          </section>

          <section>
            <h2>10. Governing Law</h2>
            <p>These terms are governed by the law of the Federal Republic of Germany. Place of jurisdiction is Berlin, where permitted.</p>
          </section>

          <section>
            <h2>11. Changes</h2>
            <p>AdTool may update these terms; new versions apply to future submissions. The legal_version attached to each consent record represents the version the Creator accepted.</p>
          </section>
        </div>
      </div>
    </>
  );
}
