import { useState, useCallback } from 'react';
import { motion, AnimatePresence } from 'framer-motion';
import { Check, FileText, Image, Play, Music, Download, Sparkles, Layout, MessageCircle, Loader2, Video } from 'lucide-react';
import { cn } from '@/lib/utils';
import { useAuth } from '@/hooks/useAuth';
import { CategorySelector } from './CategorySelector';
import { UniversalModeSelector, type UniversalGenerationMode } from './UniversalModeSelector';
import { UniversalVideoConsultant } from './UniversalVideoConsultant';
import { UniversalAutoGenerationProgress } from './UniversalAutoGenerationProgress';
import { toast } from 'sonner';
import { VIDEO_CATEGORIES, type VideoCategory, type UniversalConsultationResult } from '@/types/universal-video-creator';

// Steps for manual mode
const STEPS_MANUAL = [
  { id: 'category', label: 'Kategorie', icon: Video, description: 'Video-Typ wählen' },
  { id: 'mode-select', label: 'Modus', icon: Sparkles, description: 'Wähle deinen Weg' },
  { id: 'consultation', label: 'Beratung', icon: MessageCircle, description: 'KI-Berater' },
  { id: 'briefing', label: 'Briefing', icon: FileText, description: 'Produkt & Zielgruppe' },
  { id: 'script', label: 'Drehbuch', icon: Sparkles, description: 'KI-generiert' },
  { id: 'storyboard', label: 'Storyboard', icon: Layout, description: 'Szenen bearbeiten' },
  { id: 'visuals', label: 'Visuals', icon: Image, description: 'Assets generieren' },
  { id: 'animation', label: 'Animation', icon: Play, description: 'Bewegung & Übergänge' },
  { id: 'audio', label: 'Audio', icon: Music, description: 'Voice-Over & Musik' },
  { id: 'export', label: 'Export', icon: Download, description: 'Rendern & Download' },
];

// Steps for full-service mode  
const STEPS_FULL_SERVICE = [
  { id: 'category', label: 'Kategorie', icon: Video, description: 'Video-Typ wählen' },
  { id: 'mode-select', label: 'Modus', icon: Sparkles, description: 'Wähle deinen Weg' },
  { id: 'consultation', label: 'Beratung', icon: MessageCircle, description: '20-24 Phasen Interview' },
  { id: 'generating', label: 'KI erstellt', icon: Loader2, description: 'Automatisch' },
  { id: 'preview', label: 'Vorschau', icon: Play, description: 'Live-Preview' },
  { id: 'export', label: 'Download', icon: Download, description: '3 Formate' },
];

export function UniversalVideoWizard() {
  const { user } = useAuth();
  const [selectedCategory, setSelectedCategory] = useState<VideoCategory | null>(null);
  const [generationMode, setGenerationMode] = useState<UniversalGenerationMode | null>(null);
  const [currentStep, setCurrentStep] = useState(0);
  const [isAutoGenerating, setIsAutoGenerating] = useState(false);
  const [consultationResult, setConsultationResult] = useState<UniversalConsultationResult | null>(null);
  const [autoGeneratedProject, setAutoGeneratedProject] = useState<any>(null);

  // Select steps based on mode
  const STEPS = generationMode === 'full-service' ? STEPS_FULL_SERVICE : 
                generationMode === 'manual' ? STEPS_MANUAL :
                [{ id: 'category', label: 'Kategorie', icon: Video, description: 'Video-Typ wählen' }];

  const handleCategorySelect = (category: VideoCategory) => {
    setSelectedCategory(category);
  };

  const handleCategoryConfirm = () => {
    if (selectedCategory) {
      setCurrentStep(1); // Move to mode selection
    }
  };

  const handleModeSelect = (mode: UniversalGenerationMode) => {
    setGenerationMode(mode);
    setCurrentStep(2); // Move to consultation step
  };

  const handleBackToCategory = () => {
    setSelectedCategory(null);
    setGenerationMode(null);
    setCurrentStep(0);
  };

  const handleConsultationComplete = (result: UniversalConsultationResult) => {
    setConsultationResult(result);
    
    if (generationMode === 'full-service') {
      setIsAutoGenerating(true);
      setCurrentStep(3); // Move to generating step
    } else {
      // Manual mode - go to briefing
      setCurrentStep(3);
    }
  };

  const handleConsultationSkip = () => {
    if (generationMode === 'full-service') {
      return; // Can't skip in full-service
    }
    setCurrentStep(3); // Skip to briefing
  };

  const handleAutoGenerationComplete = (project: any) => {
    setAutoGeneratedProject(project);
    setIsAutoGenerating(false);
    setCurrentStep(4); // Move to preview step
    toast.success('🎬 Video erfolgreich erstellt!');
  };

  const handleSwitchToManual = (partialProject: any) => {
    setGenerationMode('manual');
    setIsAutoGenerating(false);
    setAutoGeneratedProject(partialProject);
    
    if (partialProject?.script) {
      setCurrentStep(5); // Storyboard step
    } else {
      setCurrentStep(3); // Briefing step
    }
  };

  const currentStepId = STEPS[currentStep]?.id;
  const categoryInfo = selectedCategory ? VIDEO_CATEGORIES.find(c => c.category === selectedCategory) : null;

  return (
    <div className="max-w-7xl mx-auto">
      {/* Stepper - show after category selection */}
      {selectedCategory && generationMode && (
        <div className="mb-8 overflow-x-auto pb-2">
          <div className="flex items-center justify-between min-w-max gap-2">
            {STEPS.map((step, index) => {
              const Icon = step.icon;
              const isActive = index === currentStep;
              const isCompleted = index < currentStep;

              return (
                <div key={step.id} className="flex items-center">
                  <motion.button
                    onClick={() => index < currentStep && setCurrentStep(index)}
                    disabled={index > currentStep}
                    className={cn(
                      'flex items-center gap-2 px-4 py-2.5 rounded-xl transition-all duration-300',
                      'border backdrop-blur-sm',
                      isActive && 'bg-[#F5C76A]/20 border-[#F5C76A]/50 text-[#F5C76A] shadow-[0_0_20px_rgba(245,199,106,0.3)]',
                      isCompleted && 'bg-[#F5C76A]/10 border-[#F5C76A]/30 text-[#F5C76A] cursor-pointer hover:bg-[#F5C76A]/20',
                      !isActive && !isCompleted && 'bg-muted/20 border-white/10 text-muted-foreground'
                    )}
                    whileHover={isCompleted ? { scale: 1.02 } : {}}
                    whileTap={isCompleted ? { scale: 0.98 } : {}}
                  >
                    <div className={cn(
                      'w-8 h-8 rounded-lg flex items-center justify-center',
                      isActive && 'bg-[#F5C76A] text-black',
                      isCompleted && 'bg-[#F5C76A]/30 text-[#F5C76A]',
                      !isActive && !isCompleted && 'bg-muted/30 text-muted-foreground'
                    )}>
                      {isCompleted ? (
                        <Check className="h-4 w-4" />
                      ) : (
                        <Icon className={cn("h-4 w-4", step.id === 'generating' && isActive && "animate-spin")} />
                      )}
                    </div>
                    <div className="hidden lg:block text-left">
                      <div className="text-sm font-medium">{step.label}</div>
                      <div className="text-xs text-muted-foreground">{step.description}</div>
                    </div>
                  </motion.button>
                  {index < STEPS.length - 1 && (
                    <div
                      className={cn(
                        'h-px w-6 lg:w-10 mx-1',
                        isCompleted ? 'bg-[#F5C76A]' : 'bg-border'
                      )}
                    />
                  )}
                </div>
              );
            })}
          </div>
        </div>
      )}

      {/* Step Content */}
      <AnimatePresence mode="wait">
        <motion.div
          key={currentStepId}
          initial={{ opacity: 0, y: 20 }}
          animate={{ opacity: 1, y: 0 }}
          exit={{ opacity: 0, y: -20 }}
          transition={{ duration: 0.3 }}
        >
          {/* Category Selection */}
          {currentStepId === 'category' && (
            <div className="space-y-6">
              <CategorySelector
                selectedCategory={selectedCategory}
                onSelectCategory={handleCategorySelect}
              />
              {selectedCategory && (
                <motion.div
                  initial={{ opacity: 0, y: 20 }}
                  animate={{ opacity: 1, y: 0 }}
                  className="flex justify-center"
                >
                  <button
                    onClick={handleCategoryConfirm}
                    className={cn(
                      "px-8 py-3 rounded-xl font-semibold text-black",
                      "bg-gradient-to-r from-[#F5C76A] to-amber-500",
                      "hover:shadow-[0_0_30px_rgba(245,199,106,0.4)]",
                      "transition-all duration-300"
                    )}
                  >
                    Mit {categoryInfo?.name} fortfahren
                  </button>
                </motion.div>
              )}
            </div>
          )}

          {/* Mode Selection */}
          {currentStepId === 'mode-select' && selectedCategory && (
            <UniversalModeSelector
              selectedCategory={selectedCategory}
              onSelectMode={handleModeSelect}
              onBack={handleBackToCategory}
            />
          )}

          {/* Consultation */}
          {currentStepId === 'consultation' && selectedCategory && generationMode && (
            <UniversalVideoConsultant
              category={selectedCategory}
              mode={generationMode}
              onConsultationComplete={handleConsultationComplete}
              onSkip={handleConsultationSkip}
            />
          )}

          {/* Auto Generation (Full-Service) */}
          {currentStepId === 'generating' && isAutoGenerating && consultationResult && selectedCategory && user && (
            <UniversalAutoGenerationProgress
              consultationResult={consultationResult}
              category={selectedCategory}
              userId={user.id}
              onComplete={handleAutoGenerationComplete}
              onSwitchToManual={handleSwitchToManual}
            />
          )}

          {/* Preview (Full-Service after generation) */}
          {currentStepId === 'preview' && autoGeneratedProject && (
            <div className="text-center py-12">
              <div className="w-20 h-20 rounded-full bg-[#F5C76A]/20 flex items-center justify-center mx-auto mb-6">
                <Play className="h-10 w-10 text-[#F5C76A]" />
              </div>
              <h2 className="text-2xl font-bold mb-4 text-[#F5C76A]">Video-Vorschau</h2>
              <p className="text-muted-foreground mb-6">
                Dein {categoryInfo?.name} wurde erfolgreich erstellt!
              </p>
              {/* TODO: Add UniversalPreview component */}
              <div className="bg-card/40 border border-white/10 rounded-2xl p-8 max-w-2xl mx-auto">
                <p className="text-muted-foreground">
                  🚧 Preview-Komponente wird in Phase 4 implementiert
                </p>
              </div>
            </div>
          )}

          {/* Manual Mode Steps - Placeholder for now */}
          {generationMode === 'manual' && ['briefing', 'script', 'storyboard', 'visuals', 'animation', 'audio', 'export'].includes(currentStepId || '') && (
            <div className="text-center py-12">
              <div className="w-20 h-20 rounded-full bg-muted/20 flex items-center justify-center mx-auto mb-6">
                <FileText className="h-10 w-10 text-muted-foreground" />
              </div>
              <h2 className="text-2xl font-bold mb-4">
                {STEPS.find(s => s.id === currentStepId)?.label}
              </h2>
              <p className="text-muted-foreground mb-6">
                Dieser Schritt wird in Phase 4 implementiert
              </p>
              <div className="flex gap-4 justify-center">
                <button
                  onClick={() => setCurrentStep(Math.max(0, currentStep - 1))}
                  className="px-6 py-2 rounded-xl border border-white/10 hover:bg-white/5 transition-colors"
                >
                  Zurück
                </button>
                <button
                  onClick={() => setCurrentStep(Math.min(STEPS.length - 1, currentStep + 1))}
                  className="px-6 py-2 rounded-xl bg-[#F5C76A] text-black font-semibold hover:shadow-[0_0_20px_rgba(245,199,106,0.4)] transition-all"
                >
                  Weiter
                </button>
              </div>
            </div>
          )}
        </motion.div>
      </AnimatePresence>
    </div>
  );
}
