import { useState, useCallback, useEffect, useRef } from 'react';
import { motion, AnimatePresence } from 'framer-motion';
import { Check, FileText, Image, Play, Music, Download, Sparkles, Layout, MessageCircle, Loader2, Video, AlertTriangle, RefreshCw, ArrowLeft, RotateCcw, Palette, Film } from 'lucide-react';
import { cn } from '@/lib/utils';
import { useAuth } from '@/hooks/useAuth';
import { Button } from '@/components/ui/button';
import { CategorySelector } from './CategorySelector';
import { MoodPresetSelector, type MoodConfig } from './MoodPresetSelector';
import { FilmStyleSelector } from './FilmStyleSelector';
import { UniversalModeSelector, type UniversalGenerationMode } from './UniversalModeSelector';
import { UniversalVideoConsultant } from './UniversalVideoConsultant';
import { UniversalAutoGenerationProgress } from './UniversalAutoGenerationProgress';
import { UniversalPreviewPlayer } from './UniversalPreviewPlayer';
import { UniversalExportStep } from './UniversalExportStep';
import { toast } from 'sonner';
import { VIDEO_CATEGORIES, type VideoCategory, type UniversalConsultationResult, type UniversalVideoStyle } from '@/types/universal-video-creator';
import { Dialog, DialogContent, DialogHeader, DialogTitle, DialogDescription, DialogFooter } from '@/components/ui/dialog';
import { getWizardDraft, saveWizardDraft, clearAllDrafts, hasMeaningfulDraft } from '@/lib/universal-video-draft';

// Steps for manual mode
const STEPS_MANUAL = [
  { id: 'category', label: 'Kategorie', icon: Video, description: 'Video-Typ wählen' },
  { id: 'mood', label: 'Stimmung', icon: Palette, description: 'Stil & Stimmung' },
  { id: 'visual-style', label: 'Filmart', icon: Film, description: 'Visueller Stil' },
  { id: 'mode-select', label: 'Modus', icon: Sparkles, description: 'Wähle deinen Weg' },
  { id: 'consultation', label: 'Beratung', icon: MessageCircle, description: 'KI-Berater' },
  { id: 'briefing', label: 'Briefing', icon: FileText, description: 'Produkt & Zielgruppe' },
  { id: 'script', label: 'Drehbuch', icon: Sparkles, description: 'KI-generiert' },
  { id: 'storyboard', label: 'Storyboard', icon: Layout, description: 'Szenen bearbeiten' },
  { id: 'visuals', label: 'Visuals', icon: Image, description: 'Assets generieren' },
  { id: 'animation', label: 'Animation', icon: Play, description: 'Bewegung & Übergänge' },
  { id: 'audio', label: 'Audio', icon: Music, description: 'Voice-Over & Musik' },
  { id: 'export', label: 'Export', icon: Download, description: 'Rendern & Download' },
];

// Steps for full-service mode  
const STEPS_FULL_SERVICE = [
  { id: 'category', label: 'Kategorie', icon: Video, description: 'Video-Typ wählen' },
  { id: 'mood', label: 'Stimmung', icon: Palette, description: 'Stil & Stimmung' },
  { id: 'visual-style', label: 'Filmart', icon: Film, description: 'Visueller Stil' },
  { id: 'mode-select', label: 'Modus', icon: Sparkles, description: 'Wähle deinen Weg' },
  { id: 'consultation', label: 'Beratung', icon: MessageCircle, description: '20-24 Phasen Interview' },
  { id: 'generating', label: 'KI erstellt', icon: Loader2, description: 'Automatisch' },
  { id: 'preview', label: 'Vorschau', icon: Play, description: 'Live-Preview' },
  { id: 'export', label: 'Download', icon: Download, description: '3 Formate' },
];

// Validate consultation result has minimum required data
const validateConsultationResult = (result: UniversalConsultationResult): { valid: boolean; errors: string[] } => {
  const errors: string[] = [];
  
  if (!result.category) errors.push('Kategorie fehlt');
  if (!result.productDescription && !result.productName) errors.push('Produktbeschreibung fehlt');
  if (!result.storytellingStructure) errors.push('Storytelling-Struktur fehlt');
  
  return { valid: errors.length === 0, errors };
};

export function UniversalVideoWizard() {
  const { user } = useAuth();
  
  // Draft recovery dialog state
  const [showDraftDialog, setShowDraftDialog] = useState(false);
  const [draftChecked, setDraftChecked] = useState(false);
  
  const [selectedCategory, setSelectedCategory] = useState<VideoCategory | null>(null);
  const [generationMode, setGenerationMode] = useState<UniversalGenerationMode | null>(null);
  const [currentStep, setCurrentStep] = useState(0);
  const [isAutoGenerating, setIsAutoGenerating] = useState(false);
  const [consultationResult, setConsultationResult] = useState<UniversalConsultationResult | null>(null);
  const [autoGeneratedProject, setAutoGeneratedProject] = useState<any>(null);
  const activeProgressIdRef = useRef<string | null>(null);
  const generationStartedAtRef = useRef<string | null>(null);
  const [moodConfig, setMoodConfig] = useState<MoodConfig | null>(null);
  const [selectedVisualStyle, setSelectedVisualStyle] = useState<UniversalVideoStyle | null>(null);
  const [error, setError] = useState<string | null>(null);
  const [retryCount, setRetryCount] = useState(0);
  const [rateLimitRetryKey, setRateLimitRetryKey] = useState(0);

  // Check for draft on mount — show dialog if meaningful draft exists
  useEffect(() => {
    if (draftChecked) return;
    setDraftChecked(true);
    
    if (hasMeaningfulDraft()) {
      setShowDraftDialog(true);
    }
  }, [draftChecked]);

  const handleResumeDraft = () => {
    const draft = getWizardDraft();
    if (draft) {
      setSelectedCategory(draft.category as VideoCategory | null);
      setGenerationMode(draft.mode as UniversalGenerationMode | null);
      setCurrentStep(draft.step || 0);
      setMoodConfig(draft.moodConfig || null);
      setConsultationResult(draft.consultationResult || null);
      setAutoGeneratedProject(draft.autoGeneratedProject || null);
    }
    setShowDraftDialog(false);
  };

  const handleStartFresh = () => {
    clearAllDrafts();
    setShowDraftDialog(false);
  };

  // Persist wizard state to localStorage
  useEffect(() => {
    if (selectedCategory || generationMode || currentStep > 0) {
      saveWizardDraft({
        category: selectedCategory,
        mode: generationMode,
        step: currentStep,
        moodConfig,
        consultationResult,
        autoGeneratedProject,
      });
    }
  }, [selectedCategory, generationMode, currentStep, moodConfig, consultationResult, autoGeneratedProject]);

  // r54b: Fallback — recover from DB when on generating (done) or preview step without project
  const dbFallbackAttempted = useRef(false);
  useEffect(() => {
    const isStuckOnGenerating = currentStep === 5 && !isAutoGenerating && !autoGeneratedProject;
    const isPreviewWithoutProject = currentStep === 6 && !autoGeneratedProject;
    
    if ((isStuckOnGenerating || isPreviewWithoutProject) && user && !dbFallbackAttempted.current) {
      dbFallbackAttempted.current = true;
      console.log('[UniversalVideoWizard] Phase12 DB recovery triggered, step=', currentStep);
      import('@/integrations/supabase/client').then(({ supabase }) => {
        let query = supabase
          .from('universal_video_progress')
          .select('result_data')
          .eq('user_id', user.id)
          .eq('status', 'completed')
          .order('updated_at', { ascending: false })
          .limit(1);
        
        if (generationStartedAtRef.current) {
          query = query.gte('created_at', generationStartedAtRef.current);
        }
        
        query.single()
          .then(({ data }) => {
            if (data?.result_data) {
              const rd = data.result_data as any;
              const recovered = {
                outputUrl: rd.outputUrl || rd.output_url,
                renderId: rd.renderId || rd.render_id,
                ...rd,
              };
              if (recovered.outputUrl) {
                console.log('[UniversalVideoWizard] Phase12: Recovered project from DB:', recovered.outputUrl);
                setAutoGeneratedProject(recovered);
                if (currentStep === 5) {
                  setCurrentStep(6);
                }
              }
            }
          });
      });
    }
  }, [currentStep, autoGeneratedProject, user, isAutoGenerating]);

  // Select steps based on mode
  const STEPS = generationMode === 'full-service' ? STEPS_FULL_SERVICE : 
                generationMode === 'manual' ? STEPS_MANUAL :
                [
                  { id: 'category', label: 'Kategorie', icon: Video, description: 'Video-Typ wählen' },
                  { id: 'mood', label: 'Stimmung', icon: Palette, description: 'Stil & Stimmung' },
                  { id: 'visual-style', label: 'Filmart', icon: Film, description: 'Visueller Stil' },
                  { id: 'mode-select', label: 'Modus', icon: Sparkles, description: 'Wähle deinen Weg' }
                ];

  const handleCategorySelect = (category: VideoCategory) => {
    setSelectedCategory(category);
    setError(null);
  };

  const handleCategoryConfirm = () => {
    if (selectedCategory) {
      setCurrentStep(1);
    }
  };

  const handleMoodConfirm = (config: MoodConfig) => {
    setMoodConfig(config);
    setCurrentStep(2); // → visual-style
  };

  const handleVisualStyleConfirm = (style: UniversalVideoStyle) => {
    setSelectedVisualStyle(style);
    setCurrentStep(3); // → mode-select
  };

  const handleModeSelect = (mode: UniversalGenerationMode) => {
    setGenerationMode(mode);
    setCurrentStep(4); // → consultation
  };

  const handleBackToCategory = () => {
    setSelectedCategory(null);
    setGenerationMode(null);
    setCurrentStep(0);
    setError(null);
    // Don't clear drafts on back — only on explicit reset
  };

  const handleResetWizard = () => {
    setSelectedCategory(null);
    setGenerationMode(null);
    setMoodConfig(null);
    setCurrentStep(0);
    setError(null);
    setIsAutoGenerating(false);
    setAutoGeneratedProject(null);
    setConsultationResult(null);
    clearAllDrafts();
  };

  const handleConsultationComplete = (result: UniversalConsultationResult) => {
    const validation = validateConsultationResult(result);
    if (!validation.valid) {
      console.warn('[UniversalVideoWizard] Consultation result validation failed:', validation.errors);
      result.storytellingStructure = result.storytellingStructure || 'problem-solution';
      result.productDescription = result.productDescription || result.productName || 'Video-Projekt';
    }

    if (moodConfig) {
      result.moodConfig = moodConfig;
    }

    // Inject pre-selected visual style
    if (selectedVisualStyle) {
      result.visualStyle = selectedVisualStyle;
    }

    setConsultationResult(result);
    setError(null);
    
    if (generationMode === 'full-service') {
      setAutoGeneratedProject(null);
      activeProgressIdRef.current = null;
      generationStartedAtRef.current = new Date().toISOString();
      dbFallbackAttempted.current = false;
      
      setIsAutoGenerating(true);
      setCurrentStep(5); // → generating
      toast.info('🚀 Video-Generierung gestartet!');
    } else {
      setCurrentStep(5);
    }
  };

  const handleConsultationSkip = () => {
    if (generationMode === 'full-service') {
      toast.error('Im Full-Service-Modus ist die Beratung erforderlich');
      return;
    }
    const defaultResult: UniversalConsultationResult = {
      category: selectedCategory!,
      projectName: `${VIDEO_CATEGORIES.find(c => c.category === selectedCategory)?.name || 'Video'}-Projekt`,
      completedAt: new Date().toISOString(),
      companyName: '',
      productName: '',
      productDescription: '',
      targetAudience: '',
      coreProblem: '',
      solution: '',
      uniqueSellingPoints: [],
      storytellingStructure: 'problem-solution',
      emotionalTone: 'professional',
      keyMessage: '',
      desiredAction: '',
      ctaText: '',
      visualStyle: 'flat-design',
      brandColors: [],
      hasCharacter: false,
      voiceGender: 'male',
      voiceLanguage: 'de',
      voiceTone: 'professionell',
      musicStyle: 'corporate',
      musicMood: 'inspirational',
      videoDuration: 60,
      aspectRatio: '16:9',
      outputFormats: ['16:9'],
      categorySpecific: {},
      briefingSummary: '',
    };
    setConsultationResult(defaultResult);
    setCurrentStep(4); // → consultation
  };

  const handleAutoGenerationComplete = (project: any) => {
    if (!project || !project.outputUrl) {
      console.warn('[UniversalVideoWizard] Phase12: onComplete called without valid project, staying in error state');
      setError('Video-Generierung fehlgeschlagen. Bitte versuche es erneut.');
      setIsAutoGenerating(false);
      return;
    }
    
    setAutoGeneratedProject(project);
    setIsAutoGenerating(false);
    setCurrentStep(6); // → preview
    toast.success('🎬 Video erfolgreich erstellt!');
    
    // Don't clear consultant state here — keep draft until user explicitly starts new video
  };

  const handleAutoGenerationError = (errorMessage: string) => {
    setError(errorMessage);
    setIsAutoGenerating(false);
  };

  const handleSwitchToManual = (partialProject: any) => {
    setGenerationMode('manual');
    setIsAutoGenerating(false);
    setAutoGeneratedProject(partialProject);
    setError(null);
    
    if (partialProject?.script) {
      setCurrentStep(5);
    } else {
      setCurrentStep(3);
    }
    toast.info('Zum manuellen Modus gewechselt');
  };

  const MAX_AUTO_RETRIES = 9;
  const getDiagnosticProfile = (retry: number): string => {
    const profiles = ['A', 'B', 'C', 'D', 'E', 'F', 'G', 'H', 'I', 'J'];
    return profiles[Math.min(retry, profiles.length - 1)];
  };

  const handleRetry = () => {
    console.log('[UniversalVideoWizard] handleRetry called, current isAutoGenerating:', isAutoGenerating);
    setError(null);
    setIsAutoGenerating(false);
    setAutoGeneratedProject(null);
    generationStartedAtRef.current = new Date().toISOString();
    dbFallbackAttempted.current = false;
    
    const newRetryCount = retryCount + 1;
    
    if (newRetryCount > MAX_AUTO_RETRIES) {
      console.log(`[UniversalVideoWizard] Max retries (${MAX_AUTO_RETRIES}) reached, showing final error`);
      setError('Alle Diagnoseprofile (A–O) getestet – der Fehler tritt weiterhin auf. Bitte kontaktiere den Support.');
      return;
    }
    
    setRetryCount(newRetryCount);
    
    const diagProfile = getDiagnosticProfile(newRetryCount);
    console.log(`[UniversalVideoWizard] Retry #${newRetryCount}/${MAX_AUTO_RETRIES}, diagnosticProfile=${diagProfile}`);
    toast.info(`🔍 Diagnose-Profil ${diagProfile} wird getestet... (${newRetryCount}/${MAX_AUTO_RETRIES})`);
    
    setTimeout(() => {
      if (consultationResult && generationMode === 'full-service') {
        console.log('[UniversalVideoWizard] Re-mounting with isAutoGenerating=true, profile:', diagProfile);
        setIsAutoGenerating(true);
        setCurrentStep(3);
      }
    }, 150);
  };

  const handleRateLimitRetry = () => {
    const diagProfile = getDiagnosticProfile(retryCount);
    console.log(`[UniversalVideoWizard] Rate-limit retry with SAME profile ${diagProfile} (retryCount stays ${retryCount})`);
    setError(null);
    setIsAutoGenerating(false);
    setRateLimitRetryKey(prev => prev + 1);
    setTimeout(() => {
      if (consultationResult && generationMode === 'full-service') {
        setIsAutoGenerating(true);
        setCurrentStep(3);
      }
    }, 150);
  };

  const handleBackToConsultation = () => {
    setCurrentStep(3);
    setIsAutoGenerating(false);
    setError(null);
  };

  const handleBack = () => {
    if (currentStep > 0) {
      setCurrentStep(currentStep - 1);
      setError(null);
    }
  };

  const currentStepId = STEPS[currentStep]?.id;
  const categoryInfo = selectedCategory ? VIDEO_CATEGORIES.find(c => c.category === selectedCategory) : null;

  // Auth check
  if (!user) {
    return (
      <div className="max-w-xl mx-auto text-center py-12">
        <div className="w-20 h-20 rounded-full bg-muted/20 flex items-center justify-center mx-auto mb-6 border border-white/10">
          <AlertTriangle className="h-10 w-10 text-amber-500" />
        </div>
        <h2 className="text-2xl font-bold mb-4">Anmeldung erforderlich</h2>
        <p className="text-muted-foreground mb-6">
          Bitte melde dich an, um den Universal Video Creator zu nutzen.
        </p>
      </div>
    );
  }

  return (
    <div className="max-w-7xl mx-auto">
      {/* Draft Recovery Dialog */}
      <Dialog open={showDraftDialog} onOpenChange={setShowDraftDialog}>
        <DialogContent className="sm:max-w-md">
          <DialogHeader>
            <DialogTitle className="flex items-center gap-2">
              <FileText className="h-5 w-5 text-[#F5C76A]" />
              Entwurf gefunden
            </DialogTitle>
            <DialogDescription>
              Du hast ein begonnenes Video-Interview. Möchtest du dort weitermachen oder neu starten?
            </DialogDescription>
          </DialogHeader>
          <DialogFooter className="flex gap-2 sm:gap-2">
            <Button variant="outline" onClick={handleStartFresh}>
              <RotateCcw className="h-4 w-4 mr-2" />
              Neu starten
            </Button>
            <Button onClick={handleResumeDraft} className="bg-gradient-to-r from-[#F5C76A] to-amber-500 text-black hover:shadow-[0_0_20px_rgba(245,199,106,0.4)]">
              <Play className="h-4 w-4 mr-2" />
              Fortfahren
            </Button>
          </DialogFooter>
        </DialogContent>
      </Dialog>

      {/* Global Error Banner */}
      {error && (
        <motion.div
          initial={{ opacity: 0, y: -20 }}
          animate={{ opacity: 1, y: 0 }}
          className="mb-6 p-4 bg-destructive/10 border border-destructive/30 rounded-xl flex items-center justify-between"
        >
          <div className="flex items-center gap-3">
            <AlertTriangle className="h-5 w-5 text-destructive" />
            <span className="text-sm">{error}</span>
          </div>
          <div className="flex gap-2">
            <Button variant="ghost" size="sm" onClick={() => setError(null)}>
              Schließen
            </Button>
            <Button variant="outline" size="sm" onClick={handleBackToConsultation} className="border-muted">
              <ArrowLeft className="h-4 w-4 mr-2" />
              Zurück zum Interview
            </Button>
            <Button variant="outline" size="sm" onClick={handleRetry} className="border-destructive/30">
              <RefreshCw className="h-4 w-4 mr-2" />
              Erneut versuchen
            </Button>
          </div>
        </motion.div>
      )}

      {/* Back Button + Reset Button - when in wizard */}
      {currentStep > 0 && (
        <motion.div
          initial={{ opacity: 0 }}
          animate={{ opacity: 1 }}
          className="mb-4 flex items-center gap-2"
        >
          {currentStepId !== 'generating' && (
            <Button variant="ghost" size="sm" onClick={handleBack} className="text-muted-foreground hover:text-foreground">
              <ArrowLeft className="h-4 w-4 mr-2" />
              Zurück
            </Button>
          )}
          <Button variant="outline" size="sm" onClick={handleResetWizard}>
            <RotateCcw className="h-4 w-4 mr-2" />
            Neues Video starten
          </Button>
        </motion.div>
      )}

      {/* Stepper - show after category selection */}
      {selectedCategory && generationMode && (
        <div className="mb-8 overflow-x-auto pb-2">
          <div className="flex items-center justify-between min-w-max gap-2">
            {STEPS.map((step, index) => {
              const Icon = step.icon;
              const isActive = index === currentStep;
              const isCompleted = index < currentStep;

              return (
                <div key={step.id} className="flex items-center">
                  <motion.button
                    onClick={() => index < currentStep && setCurrentStep(index)}
                    disabled={index > currentStep}
                    className={cn(
                      'flex items-center gap-2 px-4 py-2.5 rounded-xl transition-all duration-300',
                      'border backdrop-blur-sm',
                      isActive && 'bg-[#F5C76A]/20 border-[#F5C76A]/50 text-[#F5C76A] shadow-[0_0_20px_rgba(245,199,106,0.3)]',
                      isCompleted && 'bg-[#F5C76A]/10 border-[#F5C76A]/30 text-[#F5C76A] cursor-pointer hover:bg-[#F5C76A]/20',
                      !isActive && !isCompleted && 'bg-muted/20 border-white/10 text-muted-foreground'
                    )}
                    whileHover={isCompleted ? { scale: 1.02 } : {}}
                    whileTap={isCompleted ? { scale: 0.98 } : {}}
                  >
                    <div className={cn(
                      'w-8 h-8 rounded-lg flex items-center justify-center',
                      isActive && 'bg-[#F5C76A] text-black',
                      isCompleted && 'bg-[#F5C76A]/30 text-[#F5C76A]',
                      !isActive && !isCompleted && 'bg-muted/30 text-muted-foreground'
                    )}>
                      {isCompleted ? (
                        <Check className="h-4 w-4" />
                      ) : (
                        <Icon className={cn("h-4 w-4", step.id === 'generating' && isActive && "animate-spin")} />
                      )}
                    </div>
                    <div className="hidden lg:block text-left">
                      <div className="text-sm font-medium">{step.label}</div>
                      <div className="text-xs text-muted-foreground">{step.description}</div>
                    </div>
                  </motion.button>
                  {index < STEPS.length - 1 && (
                    <div
                      className={cn(
                        'h-px w-6 lg:w-10 mx-1',
                        isCompleted ? 'bg-[#F5C76A]' : 'bg-border'
                      )}
                    />
                  )}
                </div>
              );
            })}
          </div>
        </div>
      )}

      {/* Step Content */}
      <AnimatePresence mode="wait">
        <motion.div
          key={currentStepId}
          initial={{ opacity: 0, y: 20 }}
          animate={{ opacity: 1, y: 0 }}
          exit={{ opacity: 0, y: -20 }}
          transition={{ duration: 0.3 }}
        >
          {/* Category Selection */}
          {currentStepId === 'category' && (
            <div className="space-y-6">
              <CategorySelector
                selectedCategory={selectedCategory}
                onSelectCategory={handleCategorySelect}
              />
              {selectedCategory && (
                <motion.div
                  initial={{ opacity: 0, y: 20 }}
                  animate={{ opacity: 1, y: 0 }}
                  className="flex justify-center"
                >
                  <button
                    onClick={handleCategoryConfirm}
                    className={cn(
                      "px-8 py-3 rounded-xl font-semibold text-black",
                      "bg-gradient-to-r from-[#F5C76A] to-amber-500",
                      "hover:shadow-[0_0_30px_rgba(245,199,106,0.4)]",
                      "transition-all duration-300"
                    )}
                  >
                    Mit {categoryInfo?.name} fortfahren
                  </button>
                </motion.div>
              )}
            </div>
          )}

          {/* Mood Selection */}
          {currentStepId === 'mood' && selectedCategory && (
            <MoodPresetSelector onConfirm={handleMoodConfirm} />
          )}

          {/* Mode Selection */}
          {currentStepId === 'mode-select' && selectedCategory && (
            <UniversalModeSelector
              selectedCategory={selectedCategory}
              onSelectMode={handleModeSelect}
              onBack={handleBackToCategory}
            />
          )}

          {/* Consultation */}
          {currentStepId === 'consultation' && selectedCategory && generationMode && (
            <UniversalVideoConsultant
              category={selectedCategory}
              mode={generationMode}
              onConsultationComplete={handleConsultationComplete}
              onSkip={handleConsultationSkip}
            />
          )}

          {/* Auto Generation (Full-Service) */}
          {currentStepId === 'generating' && isAutoGenerating && consultationResult && selectedCategory && user && (
            <UniversalAutoGenerationProgress
              key={`gen-${retryCount}-rl-${rateLimitRetryKey}`}
              consultationResult={consultationResult}
              category={selectedCategory}
              userId={user.id}
              onComplete={handleAutoGenerationComplete}
              onSwitchToManual={handleSwitchToManual}
              onRetry={handleRetry}
              onRateLimitRetry={handleRateLimitRetry}
              diagnosticProfile={getDiagnosticProfile(retryCount)}
            />
          )}

          {/* Recovery UI when generating failed */}
          {currentStepId === 'generating' && !isAutoGenerating && !autoGeneratedProject && (
            <div className="max-w-lg mx-auto text-center py-12 space-y-6">
              {!dbFallbackAttempted.current ? (
                <>
                  <div className="w-20 h-20 rounded-full bg-muted/30 flex items-center justify-center mx-auto border border-border animate-pulse">
                    <RefreshCw className="h-10 w-10 text-muted-foreground animate-spin" />
                  </div>
                  <h2 className="text-2xl font-bold">Projekt wird geladen…</h2>
                  <p className="text-muted-foreground">Daten werden aus der Datenbank wiederhergestellt.</p>
                </>
              ) : (
                <>
                  <div className="w-20 h-20 rounded-full bg-destructive/10 flex items-center justify-center mx-auto border border-destructive/30">
                    <AlertTriangle className="h-10 w-10 text-destructive" />
                  </div>
                  <h2 className="text-2xl font-bold">Generierung fehlgeschlagen</h2>
                  <p className="text-muted-foreground">
                    {error || 'Die Video-Generierung konnte nicht abgeschlossen werden.'}
                  </p>
                  <div className="flex gap-4 justify-center">
                    <Button variant="outline" onClick={handleBackToConsultation}>
                      <ArrowLeft className="h-4 w-4 mr-2" />
                      Zurück zum Interview
                    </Button>
                    <Button onClick={handleRetry}>
                      <RefreshCw className="h-4 w-4 mr-2" />
                      Erneut versuchen
                    </Button>
                  </div>
                </>
              )}
            </div>
          )}

          {/* Preview */}
          {currentStepId === 'preview' && autoGeneratedProject && (
            <div className="space-y-6">
              <div className="text-center mb-6">
                <h2 className="text-2xl font-bold mb-2 text-[#F5C76A]">Video-Vorschau</h2>
                <p className="text-muted-foreground">
                  Dein {categoryInfo?.name} wurde erfolgreich erstellt!
                </p>
              </div>
              <UniversalPreviewPlayer
                project={autoGeneratedProject}
                onExport={() => setCurrentStep(STEPS.length - 1)}
                showExportButton={true}
              />
            </div>
          )}

          {/* Export Step */}
          {currentStepId === 'export' && autoGeneratedProject && selectedCategory && user && (
            <UniversalExportStep
              project={autoGeneratedProject}
              category={selectedCategory}
              userId={user.id}
              onBack={() => setCurrentStep(currentStep - 1)}
              onComplete={(renders) => {
                toast.success(`🎬 ${renders.length} Video(s) erfolgreich exportiert!`);
              }}
            />
          )}

          {/* Manual Mode Steps - Placeholder */}
          {generationMode === 'manual' && ['briefing', 'script', 'storyboard', 'visuals', 'animation', 'audio', 'export'].includes(currentStepId || '') && (
            <div className="text-center py-12">
              <div className="w-20 h-20 rounded-full bg-muted/20 flex items-center justify-center mx-auto mb-6">
                <FileText className="h-10 w-10 text-muted-foreground" />
              </div>
              <h2 className="text-2xl font-bold mb-4">
                {STEPS.find(s => s.id === currentStepId)?.label}
              </h2>
              <p className="text-muted-foreground mb-6">
                Manueller Modus kommt bald
              </p>
              <div className="flex gap-4 justify-center">
                <button
                  onClick={() => setCurrentStep(Math.max(0, currentStep - 1))}
                  className="px-6 py-2 rounded-xl border border-white/10 hover:bg-white/5 transition-colors"
                >
                  Zurück
                </button>
                <button
                  onClick={() => setCurrentStep(Math.min(STEPS.length - 1, currentStep + 1))}
                  className="px-6 py-2 rounded-xl bg-[#F5C76A] text-black font-semibold hover:shadow-[0_0_20px_rgba(245,199,106,0.4)] transition-all"
                >
                  Weiter
                </button>
              </div>
            </div>
          )}
        </motion.div>
      </AnimatePresence>
    </div>
  );
}
