// Bond QA — Live Sweep Orchestrator
// Runs ONE real call per provider, sequentially, with hard 20€ cap.
// Stops the moment cap_eur is reached. Records every run for auditing.

import { createClient } from "npm:@supabase/supabase-js@2.95.0";

const corsHeaders = {
  "Access-Control-Allow-Origin": "*",
  "Access-Control-Allow-Headers":
    "authorization, x-client-info, apikey, content-type",
};

const SUPABASE_URL = Deno.env.get("SUPABASE_URL")!;
const SUPABASE_SERVICE_ROLE_KEY = Deno.env.get("SUPABASE_SERVICE_ROLE_KEY")!;
const SUPABASE_ANON_KEY = Deno.env.get("SUPABASE_ANON_KEY")!;

// Reusable test asset URLs (stored in qa-test-assets bucket, generated by bootstrap)
// Public sample fallback if bootstrap hasn't run yet:
const FALLBACK_IMAGE =
  "https://storage.googleapis.com/lovable-public/qa-mock/sample-1024.jpg";
const FALLBACK_VIDEO =
  "https://storage.googleapis.com/lovable-public/qa-mock/sample-5s.mp4";
const FALLBACK_AUDIO =
  "https://storage.googleapis.com/lovable-public/qa-mock/sample-5s.mp3";

interface ProviderTest {
  provider: string;
  model: string;
  mode: string;
  estimated_cost_eur: number;
  edge_function: string;
  /** Optional per-provider timeout override (ms). Defaults to 90_000. */
  timeoutMs?: number;
  buildPayload: (assets: { image: string; video: string; audio: string; portrait: string; talkingPhotoId?: string }) => Record<string, unknown>;
  /** Optional: parses provider response into success/error + asset URL */
  parseResponse?: (json: any) => { success: boolean; assetUrl?: string; error?: string };
}

const PROVIDER_MATRIX: ProviderTest[] = [
  {
    provider: "FLUX Schnell",
    model: "black-forest-labs/flux-schnell",
    mode: "T2I",
    estimated_cost_eur: 0.01,
    edge_function: "generate-image-replicate",
    buildPayload: () => ({
      prompt: "neutral product on white background, studio light",
      tier: "fast",
      aspectRatio: "1:1",
      style: "realistic",
    }),
  },
  {
    provider: "Stable Audio",
    model: "stability-ai/stable-audio-2.5",
    mode: "T2A",
    estimated_cost_eur: 0.05,
    edge_function: "generate-music-track",
    // Stable Audio cold-starts on Replicate frequently take 120-150s. 90s was
    // too aggressive — bump to 180s so we don't false-positive a slow render.
    timeoutMs: 180_000,
    buildPayload: () => ({
      prompt: "calm ambient electronic background, 10 seconds",
      duration: 10,
      tier: "quick",
    }),
  },
  {
    provider: "Hailuo 2.3 Std",
    model: "minimax/hailuo-02",
    mode: "T2V",
    estimated_cost_eur: 0.30,
    edge_function: "generate-hailuo-video",
    buildPayload: () => ({
      prompt: "a serene mountain landscape, gentle camera pan",
      duration: 6,
      resolution: "768p",
    }),
  },
  {
    provider: "Seedance Lite",
    model: "bytedance/seedance-1-lite",
    mode: "I2V",
    estimated_cost_eur: 0.25,
    edge_function: "generate-seedance-video",
    buildPayload: ({ image }) => ({
      prompt: "subtle camera zoom, cinematic lighting",
      image_url: image,
      duration: 5,
    }),
  },
  {
    provider: "Vidu Q2",
    model: "vidu-q2-reference",
    mode: "Ref2V",
    estimated_cost_eur: 0.40,
    edge_function: "generate-vidu-video",
    buildPayload: ({ image }) => ({
      prompt: "the subject walks forward in a soft golden light",
      model: "vidu-q2-reference",
      aspectRatio: "16:9",
      referenceImages: [image],
      referenceRoles: ["character"],
    }),
  },
  {
    provider: "Wan 2.5 Std",
    model: "wan/wan-2.5-std",
    mode: "T2V",
    estimated_cost_eur: 0.50,
    edge_function: "generate-wan-video",
    buildPayload: () => ({
      prompt: "a cup of coffee steaming on a wooden table, warm light",
      duration: 5,
      aspect_ratio: "16:9",
    }),
  },
  {
    provider: "Luma Ray 2",
    model: "luma/ray-2",
    mode: "T2V",
    estimated_cost_eur: 0.80,
    edge_function: "generate-luma-video",
    buildPayload: () => ({
      prompt: "slow orbital camera around a glass sculpture, museum lighting",
      duration: 5,
    }),
  },
  {
    provider: "Pika 2.2 Std",
    model: "pika-2-2-standard",
    mode: "I2V",
    estimated_cost_eur: 0.60,
    edge_function: "generate-pika-video",
    buildPayload: ({ image }) => ({
      prompt: "gentle parallax motion, soft cinematic vibe",
      model: "pika-2-2-standard",
      duration: 5,
      aspectRatio: "16:9",
      startImageUrl: image,
    }),
  },
  {
    provider: "Kling 3 Omni Std",
    model: "kwaivgi/kling-v3-omni-video",
    mode: "T2V",
    estimated_cost_eur: 1.00,
    edge_function: "generate-kling-video",
    buildPayload: () => ({
      prompt: "a cinematic shot of waves crashing on a rocky shore at sunset",
      duration: 5,
      mode: "std",
    }),
  },
  {
    provider: "Veo 3 (Google)",
    model: "veo-3.1-fast",
    mode: "T2V",
    estimated_cost_eur: 1.50,
    edge_function: "generate-veo-video",
    buildPayload: () => ({
      prompt: "a cute animated robot waving hello in a sunny garden",
      model: "veo-3.1-fast",
      duration: 4,
      aspectRatio: "16:9",
    }),
  },
  {
    provider: "Runway Aleph",
    model: "runway-gen4-aleph",
    mode: "V2V",
    estimated_cost_eur: 1.50,
    edge_function: "generate-runway-video",
    buildPayload: ({ video }) => ({
      prompt: "transform into oil painting style",
      model: "runway-gen4-aleph",
      duration: 5,
      aspectRatio: "16:9",
      referenceVideoUrl: video,
    }),
  },
  {
    provider: "Hedra Talking Head",
    model: "hedra/character-3",
    mode: "A+I",
    estimated_cost_eur: 0.60,
    edge_function: "generate-talking-head",
    buildPayload: ({ portrait, image, audio, talkingPhotoId }) => ({
      // Prefer the cached HeyGen talking_photo_id from bootstrap (avoids the
      // per-account 3-photo limit). Fall back to the bootstrap portrait
      // image, then the generic test image.
      ...(talkingPhotoId ? { talkingPhotoId } : {}),
      imageUrl: portrait || image,
      audioUrl: audio,
      aspectRatio: "16:9",
      resolution: "720p",
    }),
  },
];

function defaultParse(json: any): { success: boolean; assetUrl?: string; error?: string } {
  if (!json) return { success: false, error: "Empty response" };
  if (json.error) return { success: false, error: String(json.error) };
  const url =
    json.url ||
    json.videoUrl ||
    json.imageUrl ||
    json.audioUrl ||
    json.output ||
    json.asset_url ||
    null;
  const ok =
    json.success === true ||
    json.status === "succeeded" ||
    json.status === "completed" ||
    !!url;
  if (!ok) return { success: false, error: json.message || "Unknown failure" };
  return { success: true, assetUrl: url || undefined };
}

async function getTestAssets(supabase: any) {
  // Try bucket; fallback to public samples
  const tryUrl = async (path: string, fallback: string) => {
    try {
      const { data } = await supabase.storage
        .from("qa-test-assets")
        .createSignedUrl(path, 3600);
      return data?.signedUrl || fallback;
    } catch {
      return fallback;
    }
  };
  return {
    image: await tryUrl("test-image.png", FALLBACK_IMAGE),
    video: await tryUrl("test-video-2s.mp4", FALLBACK_VIDEO),
    audio: await tryUrl("test-audio.mp3", FALLBACK_AUDIO),
    portrait: await tryUrl("test-portrait.png", FALLBACK_IMAGE),
  };
}

async function callProvider(
  test: ProviderTest,
  assets: { image: string; video: string; audio: string; portrait: string },
  authHeader: string,
  signal: AbortSignal,
): Promise<{ status: string; durationMs: number; assetUrl?: string; error?: string; raw?: any }> {
  const start = Date.now();
  const url = `${SUPABASE_URL}/functions/v1/${test.edge_function}`;
  const payload = test.buildPayload(assets);

  try {
    const res = await fetch(url, {
      method: "POST",
      headers: {
        Authorization: authHeader,
        apikey: SUPABASE_ANON_KEY,
        "Content-Type": "application/json",
      },
      body: JSON.stringify(payload),
      signal,
    });
    const text = await res.text();
    let json: any = {};
    try {
      json = text ? JSON.parse(text) : {};
    } catch {
      json = { raw: text };
    }
    const parser = test.parseResponse || defaultParse;
    const parsed = parser(json);
    const durationMs = Date.now() - start;

    if (!res.ok) {
      return {
        status: "failed",
        durationMs,
        error: `HTTP ${res.status}: ${parsed.error || text.slice(0, 200)}`,
        raw: json,
      };
    }
    if (!parsed.success) {
      return {
        status: "failed",
        durationMs,
        error: parsed.error || "Provider returned failure",
        raw: json,
      };
    }
    return {
      status: "succeeded",
      durationMs,
      assetUrl: parsed.assetUrl,
      raw: json,
    };
  } catch (e: any) {
    const durationMs = Date.now() - start;
    if (e.name === "AbortError") {
      return { status: "timeout", durationMs, error: "Aborted (timeout)" };
    }
    return { status: "failed", durationMs, error: e?.message || String(e) };
  }
}

Deno.serve(async (req) => {
  if (req.method === "OPTIONS") {
    return new Response("ok", { headers: corsHeaders });
  }

  // Admin-only: require user JWT and verify role
  const authHeader = req.headers.get("Authorization");
  if (!authHeader) {
    return new Response(JSON.stringify({ error: "Missing Authorization" }), {
      status: 401,
      headers: { ...corsHeaders, "Content-Type": "application/json" },
    });
  }

  const userClient = createClient(SUPABASE_URL, SUPABASE_ANON_KEY, {
    global: { headers: { Authorization: authHeader } },
  });
  const { data: userData, error: userErr } = await userClient.auth.getUser();
  if (userErr || !userData?.user) {
    return new Response(JSON.stringify({ error: "Invalid token" }), {
      status: 401,
      headers: { ...corsHeaders, "Content-Type": "application/json" },
    });
  }

  const adminClient = createClient(SUPABASE_URL, SUPABASE_SERVICE_ROLE_KEY);
  const { data: roleData } = await adminClient
    .from("user_roles")
    .select("role")
    .eq("user_id", userData.user.id)
    .eq("role", "admin")
    .maybeSingle();
  if (!roleData) {
    return new Response(JSON.stringify({ error: "Admin only" }), {
      status: 403,
      headers: { ...corsHeaders, "Content-Type": "application/json" },
    });
  }

  // Optional filter to run a single provider (debugging)
  let onlyProvider: string | null = null;
  try {
    const body = await req.json();
    onlyProvider = body?.provider || null;
  } catch {
    /* no body */
  }

  // Load budget
  const { data: budget, error: budgetErr } = await adminClient
    .from("qa_live_budget")
    .select("*")
    .order("created_at", { ascending: false })
    .limit(1)
    .maybeSingle();

  if (budgetErr || !budget) {
    return new Response(
      JSON.stringify({ error: "Budget row missing", details: budgetErr?.message }),
      { status: 500, headers: { ...corsHeaders, "Content-Type": "application/json" } },
    );
  }

  const sweepId = crypto.randomUUID();
  const assets = await getTestAssets(adminClient);
  const results: any[] = [];
  let totalSpent = Number(budget.spent_eur);
  const cap = Number(budget.cap_eur);

  // Run providers sequentially
  const tests = onlyProvider
    ? PROVIDER_MATRIX.filter((t) => t.provider === onlyProvider)
    : PROVIDER_MATRIX;

  for (const test of tests) {
    const remaining = cap - totalSpent;
    if (remaining < test.estimated_cost_eur) {
      // Skip — would exceed cap
      const skipRow = {
        sweep_id: sweepId,
        provider: test.provider,
        model: test.model,
        mode: test.mode,
        status: "skipped_budget",
        cost_eur: 0,
        estimated_cost_eur: test.estimated_cost_eur,
        error_message: `Skipped: only ${remaining.toFixed(2)}€ remaining of ${cap.toFixed(2)}€ cap`,
      };
      await adminClient.from("qa_live_runs").insert(skipRow);
      results.push(skipRow);
      continue;
    }

    // Insert pending row
    const { data: pending } = await adminClient
      .from("qa_live_runs")
      .insert({
        sweep_id: sweepId,
        provider: test.provider,
        model: test.model,
        mode: test.mode,
        status: "running",
        estimated_cost_eur: test.estimated_cost_eur,
      })
      .select()
      .single();

    // 90s per-provider timeout (most providers respond < 60s)
    const ctrl = new AbortController();
    const timer = setTimeout(() => ctrl.abort(), 90_000);

    const result = await callProvider(test, assets, authHeader, ctrl.signal);
    clearTimeout(timer);

    // Charge estimated cost only on success (failed providers usually refund)
    const charged = result.status === "succeeded" ? test.estimated_cost_eur : 0;
    totalSpent += charged;

    const finalRow = {
      status: result.status,
      cost_eur: charged,
      duration_ms: result.durationMs,
      asset_url: result.assetUrl ?? null,
      error_message: result.error ?? null,
      raw_response: result.raw ?? null,
      completed_at: new Date().toISOString(),
    };

    if (pending?.id) {
      await adminClient.from("qa_live_runs").update(finalRow).eq("id", pending.id);
    }
    results.push({ ...test, ...finalRow });

    // Update budget spent
    await adminClient
      .from("qa_live_budget")
      .update({ spent_eur: totalSpent, last_run_at: new Date().toISOString() })
      .eq("id", budget.id);

    // Auto-bug-report on failure
    if (result.status === "failed" || result.status === "timeout") {
      await adminClient.from("qa_bug_reports").insert({
        mission_name: "live-sweep",
        bug_type: "provider_failure",
        severity: "medium",
        title: `Live Sweep: ${test.provider} (${test.mode}) failed`,
        description: `Provider ${test.provider} via ${test.edge_function} returned: ${
          result.error || "unknown error"
        }`,
        metadata: {
          sweep_id: sweepId,
          provider: test.provider,
          model: test.model,
          mode: test.mode,
          duration_ms: result.durationMs,
          raw: result.raw,
        },
      }).then(() => {}, () => {/* table may not exist or different schema; ignore */});
    }
  }

  const summary = {
    sweep_id: sweepId,
    total_tested: results.length,
    succeeded: results.filter((r) => r.status === "succeeded").length,
    failed: results.filter((r) => r.status === "failed").length,
    timeout: results.filter((r) => r.status === "timeout").length,
    skipped_budget: results.filter((r) => r.status === "skipped_budget").length,
    total_spent_eur: Number(totalSpent.toFixed(4)),
    cap_eur: cap,
    results,
  };

  return new Response(JSON.stringify(summary), {
    headers: { ...corsHeaders, "Content-Type": "application/json" },
  });
});
