// Bond QA — Live Sweep Orchestrator
// Runs ONE real call per provider, sequentially, with hard 20€ cap.
// Stops the moment cap_eur is reached. Records every run for auditing.

import { createClient } from "npm:@supabase/supabase-js@2.95.0";
import { ensureHeyGenTalkingPhoto } from "../_shared/heygen-bootstrap.ts";
import { recordHeartbeat } from "../_shared/heartbeat.ts";

const corsHeaders = {
  "Access-Control-Allow-Origin": "*",
  "Access-Control-Allow-Headers":
    "authorization, x-client-info, apikey, content-type",
};

const SUPABASE_URL = Deno.env.get("SUPABASE_URL")!;
const SUPABASE_SERVICE_ROLE_KEY = Deno.env.get("SUPABASE_SERVICE_ROLE_KEY")!;
const SUPABASE_ANON_KEY = Deno.env.get("SUPABASE_ANON_KEY")!;

// Reusable test asset URLs (stored in qa-test-assets bucket, generated by bootstrap)
// Public sample fallback if bootstrap hasn't run yet:
const FALLBACK_IMAGE =
  "https://storage.googleapis.com/lovable-public/qa-mock/sample-1024.jpg";
const FALLBACK_VIDEO =
  "https://storage.googleapis.com/lovable-public/qa-mock/sample-5s.mp4";
const FALLBACK_AUDIO =
  "https://storage.googleapis.com/lovable-public/qa-mock/sample-5s.mp3";

interface ProviderTest {
  provider: string;
  model: string;
  mode: string;
  estimated_cost_eur: number;
  edge_function: string;
  /** Optional per-provider timeout override (ms). Defaults to 90_000. */
  timeoutMs?: number;
  /**
   * Optional: a known/intentional non-2xx response that should NOT be
   * treated as a real failure. Used e.g. for Pika 2.2 which intentionally
   * returns HTTP 410 while the provider migration is in progress.
   */
  expectedFailure?: { status: number; reasonContains?: string; note: string };
  buildPayload: (assets: { image: string; video: string; audio: string; portrait: string; talkingPhotoId?: string }) => Record<string, unknown>;
  /** Optional: parses provider response into success/error + asset URL.
   * Set asyncStarted=true for providers that kick off a long background job
   * (e.g. HeyGen Talking Head polls 1-3min via EdgeRuntime.waitUntil).
   * The sweep marks those rows as `async_started` instead of `succeeded`. */
  parseResponse?: (json: any) => { success: boolean; assetUrl?: string; error?: string; asyncStarted?: boolean; predictionId?: string };
}

type SweepAssets = { image: string; video: string; audio: string; portrait: string; talkingPhotoId?: string };

const PROVIDER_MATRIX: ProviderTest[] = [
  {
    // NOTE: Hedra is intentionally first because it's the most expensive in
    // wall-clock time (HeyGen bootstrap + async kick-off). Running it first
    // guarantees the row is updated before the background-worker budget runs
    // out, even if a later provider is slow.
    provider: "Hedra Talking Head",
    model: "hedra/character-3",
    mode: "A+I",
    estimated_cost_eur: 0.30,
    edge_function: "generate-talking-head",
    timeoutMs: 120_000,
    buildPayload: ({ portrait, image, audio, talkingPhotoId }) => ({
      ...(talkingPhotoId ? { talkingPhotoId } : {}),
      imageUrl: portrait || image,
      audioUrl: audio,
      aspectRatio: "16:9",
      resolution: "720p",
    }),
    parseResponse: (json) => {
      if (!json) return { success: false, error: "Empty response" };
      if (json.error) return { success: false, error: String(json.error) };
      if (json.success === true && (json.status === "processing" || json.status === "pending") && !json.videoUrl) {
        return { success: true, asyncStarted: true, predictionId: json.predictionId };
      }
      return defaultParse(json);
    },
  },
  {
    provider: "FLUX Schnell",
    model: "black-forest-labs/flux-schnell",
    mode: "T2I",
    estimated_cost_eur: 0.01,
    edge_function: "generate-image-replicate",
    buildPayload: () => ({
      prompt: "neutral product on white background, studio light",
      tier: "fast",
      aspectRatio: "1:1",
      style: "realistic",
    }),
  },
  {
    provider: "Stable Audio",
    model: "stability-ai/stable-audio-2.5",
    mode: "T2A",
    estimated_cost_eur: 0.05,
    edge_function: "generate-music-track",
    // Stable Audio cold-starts on Replicate frequently take 120-150s. 90s was
    // too aggressive — bump to 180s so we don't false-positive a slow render.
    timeoutMs: 180_000,
    buildPayload: () => ({
      prompt: "calm ambient electronic background, 10 seconds",
      duration: 10,
      tier: "quick",
    }),
  },
  {
    provider: "Hailuo 2.3 Std",
    model: "minimax/hailuo-02",
    mode: "T2V",
    estimated_cost_eur: 0.30,
    edge_function: "generate-hailuo-video",
    buildPayload: () => ({
      prompt: "a serene mountain landscape, gentle camera pan",
      duration: 6,
      resolution: "768p",
    }),
  },
  {
    provider: "Seedance Lite",
    model: "bytedance/seedance-1-lite",
    mode: "I2V",
    estimated_cost_eur: 0.25,
    edge_function: "generate-seedance-video",
    buildPayload: ({ image }) => ({
      prompt: "subtle camera zoom, cinematic lighting",
      image_url: image,
      duration: 5,
    }),
  },
  {
    provider: "Vidu Q2",
    model: "vidu-q2-reference",
    mode: "Ref2V",
    estimated_cost_eur: 0.40,
    edge_function: "generate-vidu-video",
    buildPayload: ({ image }) => ({
      prompt: "the subject walks forward in a soft golden light",
      model: "vidu-q2-reference",
      aspectRatio: "16:9",
      referenceImages: [image],
      referenceRoles: ["character"],
    }),
  },
  {
    provider: "Wan 2.5 Std",
    model: "wan/wan-2.5-std",
    mode: "T2V",
    estimated_cost_eur: 0.50,
    edge_function: "generate-wan-video",
    buildPayload: () => ({
      prompt: "a cup of coffee steaming on a wooden table, warm light",
      duration: 5,
      aspect_ratio: "16:9",
    }),
  },
  {
    provider: "Luma Ray 2",
    model: "luma/ray-2",
    mode: "T2V",
    estimated_cost_eur: 0.80,
    edge_function: "generate-luma-video",
    buildPayload: () => ({
      prompt: "slow orbital camera around a glass sculpture, museum lighting",
      duration: 5,
    }),
  },
  {
    provider: "Pika 2.2 Std",
    model: "pika-2-2-standard",
    mode: "I2V",
    estimated_cost_eur: 0.60,
    edge_function: "generate-pika-video",
    // Pika 2.2 was removed from Replicate (May 2026). The edge function
    // intentionally returns HTTP 410 with PIKA_PROVIDER_MIGRATION until we
    // wire up the next provider. Treat that exact response as "expected"
    // (rendered grey "skipped" in the cockpit) rather than a real bug.
    expectedFailure: {
      status: 410,
      reasonContains: "Pika",
      note: "Provider migration in progress (intentional)",
    },
    buildPayload: ({ image }) => ({
      prompt: "gentle parallax motion, soft cinematic vibe",
      model: "pika-2-2-standard",
      duration: 5,
      aspectRatio: "16:9",
      startImageUrl: image,
    }),
  },
  {
    provider: "Kling 3 Omni Std",
    model: "kwaivgi/kling-v3-omni-video",
    mode: "T2V",
    estimated_cost_eur: 1.00,
    edge_function: "generate-kling-video",
    buildPayload: () => ({
      prompt: "a cinematic shot of waves crashing on a rocky shore at sunset",
      duration: 5,
      mode: "std",
    }),
  },
  {
    provider: "Veo 3 (Google)",
    model: "veo-3.1-fast",
    mode: "T2V",
    estimated_cost_eur: 1.50,
    edge_function: "generate-veo-video",
    buildPayload: () => ({
      prompt: "a cute animated robot waving hello in a sunny garden",
      model: "veo-3.1-fast",
      duration: 4,
      aspectRatio: "16:9",
    }),
  },
  {
    provider: "Runway Aleph",
    model: "runway-gen4-aleph",
    mode: "V2V",
    estimated_cost_eur: 1.50,
    edge_function: "generate-runway-video",
    buildPayload: ({ video }) => ({
      prompt: "transform into oil painting style",
      model: "runway-gen4-aleph",
      duration: 5,
      aspectRatio: "16:9",
      referenceVideoUrl: video,
    }),
  },
];

function defaultParse(json: any): { success: boolean; assetUrl?: string; error?: string } {
  if (!json) return { success: false, error: "Empty response" };
  if (json.error) return { success: false, error: String(json.error) };
  const url =
    json.url ||
    json.videoUrl ||
    json.imageUrl ||
    json.audioUrl ||
    json.output ||
    json.asset_url ||
    null;
  const ok =
    json.success === true ||
    json.status === "succeeded" ||
    json.status === "completed" ||
    !!url;
  if (!ok) return { success: false, error: json.message || "Unknown failure" };
  return { success: true, assetUrl: url || undefined };
}

async function getTestAssets(supabase: any) {
  // Try bucket; fallback to public samples
  const tryUrl = async (path: string, fallback: string) => {
    try {
      const { data } = await supabase.storage
        .from("qa-test-assets")
        .createSignedUrl(path, 3600);
      return data?.signedUrl || fallback;
    } catch {
      return fallback;
    }
  };

  // Read cached HeyGen talking_photo_id (set by qa-live-sweep-bootstrap).
  const readCachedTalkingPhoto = async (): Promise<string | undefined> => {
    try {
      const { data: cfg } = await supabase
        .from("system_config")
        .select("value")
        .eq("key", "qa.heygen_talking_photo_id")
        .maybeSingle();
      if (!cfg?.value) return undefined;
      if (typeof cfg.value === "string") return cfg.value;
      if (typeof cfg.value === "object" && cfg.value && "id" in cfg.value) {
        return String((cfg.value as any).id);
      }
    } catch (e) {
      console.warn("[live-sweep] read cached talking_photo_id failed:", e);
    }
    return undefined;
  };

  let talkingPhotoId = await readCachedTalkingPhoto();

  return {
    image: await tryUrl("test-image.png", FALLBACK_IMAGE),
    video: await tryUrl("test-video-2s.mp4", FALLBACK_VIDEO),
    audio: await tryUrl("test-audio.mp3", FALLBACK_AUDIO),
    portrait: await tryUrl("test-portrait.png", FALLBACK_IMAGE),
    talkingPhotoId,
  };
}

async function callProvider(
  test: ProviderTest,
  assets: SweepAssets,
  authHeader: string,
  signal: AbortSignal,
): Promise<{ status: string; durationMs: number; assetUrl?: string; error?: string; raw?: any; predictionId?: string }> {
  const start = Date.now();
  const url = `${SUPABASE_URL}/functions/v1/${test.edge_function}`;
  const payload = test.buildPayload(assets);

  try {
    const res = await fetch(url, {
      method: "POST",
      headers: {
        Authorization: authHeader,
        apikey: SUPABASE_ANON_KEY,
        "Content-Type": "application/json",
      },
      body: JSON.stringify(payload),
      signal,
    });
    const text = await res.text();
    let json: any = {};
    try {
      json = text ? JSON.parse(text) : {};
    } catch {
      json = { raw: text };
    }
    const parser = test.parseResponse || defaultParse;
    const parsed = parser(json);
    const durationMs = Date.now() - start;

    if (!res.ok) {
      // Honor expectedFailure annotation: providers that intentionally
      // return a known non-2xx (e.g. Pika 410 during provider migration)
      // should be reported as "expected" rather than counted as bugs.
      if (test.expectedFailure && res.status === test.expectedFailure.status) {
        const reasonOk = !test.expectedFailure.reasonContains
          || (parsed.error || text).toLowerCase().includes(
            test.expectedFailure.reasonContains.toLowerCase(),
          );
        if (reasonOk) {
          return {
            status: "expected",
            durationMs,
            error: `HTTP ${res.status} (expected): ${test.expectedFailure.note}`,
            raw: json,
          };
        }
      }
      return {
        status: "failed",
        durationMs,
        error: `HTTP ${res.status}: ${parsed.error || text.slice(0, 200)}`,
        raw: json,
      };
    }
    if (!parsed.success) {
      return {
        status: "failed",
        durationMs,
        error: parsed.error || "Provider returned failure",
        raw: json,
      };
    }
    if (parsed.asyncStarted) {
      return {
        status: "async_started",
        durationMs,
        assetUrl: parsed.assetUrl,
        predictionId: parsed.predictionId,
        raw: json,
      };
    }
    return {
      status: "succeeded",
      durationMs,
      assetUrl: parsed.assetUrl,
      raw: json,
    };
  } catch (e: any) {
    const durationMs = Date.now() - start;
    if (e.name === "AbortError") {
      return { status: "timeout", durationMs, error: "Aborted (timeout)" };
    }
    return { status: "failed", durationMs, error: e?.message || String(e) };
  }
}

// ----------------------------------------------------------------------------
// Background worker: runs all selected providers sequentially and updates
// the pre-inserted qa_live_runs rows in place. Triggered via
// EdgeRuntime.waitUntil so that the HTTP request can return immediately
// (avoiding the 150s edge idle timeout for long sweeps).
// ----------------------------------------------------------------------------
async function runSweep(
  adminClient: ReturnType<typeof createClient>,
  sweepId: string,
  budget: any,
  authHeader: string,
  tests: ProviderTest[],
  assets: SweepAssets,
) {
  const hbStart = Date.now();
  console.log(`[sweep ${sweepId}] start — ${tests.length} providers`);
  const cap = Number(budget.cap_eur);
  let totalSpent = 0;
  const completed: any[] = [];
  let sweepAssets = assets;

  try {
    // Important: this can take 30–150s on a cold HeyGen account. It MUST stay
    // inside waitUntil/background work; doing it in the request handler causes
    // HTTP 504 IDLE_TIMEOUT before the 202 enqueue response can be sent.
    const needsHedraBootstrap = tests.some((t) => t.edge_function === "generate-talking-head");
    if (needsHedraBootstrap && !sweepAssets.talkingPhotoId) {
      console.log(`[sweep ${sweepId}] HeyGen bootstrap queued in background…`);
      try {
        const result = await ensureHeyGenTalkingPhoto(adminClient);
        if (result.ok && result.talking_photo_id) {
          sweepAssets = { ...sweepAssets, talkingPhotoId: result.talking_photo_id };
          console.log(
            `[sweep ${sweepId}] HeyGen bootstrap ok: id=${result.talking_photo_id} reused=${result.reused} pruned=${result.pruned ?? 0}`,
          );
        } else {
          console.warn(`[sweep ${sweepId}] HeyGen bootstrap failed: ${result.error ?? "unknown"}`);
        }
      } catch (e) {
        console.warn(`[sweep ${sweepId}] HeyGen bootstrap threw:`, e);
      }
    }

    for (const test of tests) {
      const remaining = cap - totalSpent;
      if (remaining < test.estimated_cost_eur) {
        await adminClient.from("qa_live_runs").update({
          status: "skipped_budget",
          cost_eur: 0,
          error_message: `Skipped: only ${remaining.toFixed(2)}€ remaining of ${cap.toFixed(2)}€ cap`,
          completed_at: new Date().toISOString(),
        }).eq("sweep_id", sweepId).eq("provider", test.provider).eq("mode", test.mode);
        completed.push({ provider: test.provider, status: "skipped_budget" });
        continue;
      }

      // Mark as running immediately before the provider call so the UI shows
      // active progress. Slow HeyGen bootstrap already happened above in the
      // background worker, never in the HTTP request handler.
      await adminClient.from("qa_live_runs").update({
        status: "running",
        started_at: new Date().toISOString(),
      }).eq("sweep_id", sweepId).eq("provider", test.provider).eq("mode", test.mode);

      const ctrl = new AbortController();
      const timer = setTimeout(() => ctrl.abort(), test.timeoutMs ?? 90_000);
      const result = await callProvider(test, sweepAssets, authHeader, ctrl.signal);
      clearTimeout(timer);

      // Charge for both real successes and async-started jobs (the spend
      // commits to the provider the moment the kick-off returns 200).
      const charged = (result.status === "succeeded" || result.status === "async_started")
        ? test.estimated_cost_eur
        : 0;
      totalSpent += charged;

      let safeRaw: unknown = null;
      try {
        const serialized = JSON.stringify(result.raw ?? null);
        safeRaw = serialized && serialized.length > 4096
          ? { _truncated: true, preview: serialized.slice(0, 4000) }
          : (result.raw ?? null);
      } catch {
        safeRaw = { _unserializable: true };
      }

      const friendlyMessage = result.status === "async_started"
        ? `Background polling (HeyGen, 1–3 min)${result.predictionId ? ` · video_id=${result.predictionId}` : ""}`
        : (result.error ?? null);

      const { error: updErr } = await adminClient.from("qa_live_runs").update({
        status: result.status,
        cost_eur: charged,
        duration_ms: result.durationMs,
        asset_url: result.assetUrl ?? null,
        error_message: friendlyMessage,
        raw_response: safeRaw,
        completed_at: new Date().toISOString(),
      }).eq("sweep_id", sweepId).eq("provider", test.provider).eq("mode", test.mode);

      if (updErr) {
        console.error(`[sweep ${sweepId}] update failed for ${test.provider}:`, updErr.message);
      }
      completed.push({ provider: test.provider, status: result.status });
      console.log(`[sweep ${sweepId}] provider:${test.provider} → ${result.status} (${result.durationMs}ms)`);

      await adminClient.from("qa_live_budget").update({
        spent_eur: totalSpent,
        last_run_at: new Date().toISOString(),
      }).eq("id", budget.id);

      if (result.status === "failed" || result.status === "timeout") {
        await adminClient.from("qa_bug_reports").insert({
          mission_name: "live-sweep",
          bug_type: "provider_failure",
          severity: "medium",
          title: `Live Sweep: ${test.provider} (${test.mode}) failed`,
          description: `Provider ${test.provider} via ${test.edge_function} returned: ${result.error || "unknown error"}`,
          metadata: {
            sweep_id: sweepId,
            provider: test.provider,
            model: test.model,
            mode: test.mode,
            duration_ms: result.durationMs,
            raw: result.raw,
          },
        }).then(() => {}, () => {});
      }
    }

    console.log(`[sweep ${sweepId}] end — completed=${completed.length}, spent=${totalSpent.toFixed(2)}€`);
  } catch (e: any) {
    console.error(`[sweep ${sweepId}] worker crash:`, e?.message || e);
    // Mark any remaining pending/running rows as failed so the UI is unblocked
    await adminClient.from("qa_live_runs").update({
      status: "failed",
      error_message: `Worker crashed: ${e?.message || String(e)}`,
      completed_at: new Date().toISOString(),
    }).eq("sweep_id", sweepId).in("status", ["pending", "running"]);
  } finally {
    // Watchdog: even if the worker exits cleanly, sweep any rows that never
    // received a terminal status (e.g. because the worker was killed by the
    // edge runtime mid-update). Marks them as `failed` so the UI never hangs.
    const { error: watchErr } = await adminClient.from("qa_live_runs").update({
      status: "failed",
      error_message: "Worker exited before status update committed (likely runtime timeout)",
      completed_at: new Date().toISOString(),
    }).eq("sweep_id", sweepId).in("status", ["pending", "running"]);
    if (watchErr) {
      console.error(`[sweep ${sweepId}] watchdog update failed:`, watchErr.message);
    }
    await recordHeartbeat({
      jobName: "qa-live-sweep",
      status: "ok",
      durationMs: Date.now() - hbStart,
      expectedIntervalSeconds: 86400, // manually-triggered, daily expectation
    });
  }
}

Deno.serve(async (req) => {
  if (req.method === "OPTIONS") {
    return new Response("ok", { headers: corsHeaders });
  }

  // Admin-only: require user JWT and verify role
  const authHeader = req.headers.get("Authorization");
  if (!authHeader) {
    return new Response(JSON.stringify({ error: "Missing Authorization" }), {
      status: 401,
      headers: { ...corsHeaders, "Content-Type": "application/json" },
    });
  }

  const userClient = createClient(SUPABASE_URL, SUPABASE_ANON_KEY, {
    global: { headers: { Authorization: authHeader } },
  });
  const { data: userData, error: userErr } = await userClient.auth.getUser();
  if (userErr || !userData?.user) {
    return new Response(JSON.stringify({ error: "Invalid token" }), {
      status: 401,
      headers: { ...corsHeaders, "Content-Type": "application/json" },
    });
  }

  const adminClient = createClient(SUPABASE_URL, SUPABASE_SERVICE_ROLE_KEY);
  const { data: roleData } = await adminClient
    .from("user_roles")
    .select("role")
    .eq("user_id", userData.user.id)
    .eq("role", "admin")
    .maybeSingle();
  if (!roleData) {
    return new Response(JSON.stringify({ error: "Admin only" }), {
      status: 403,
      headers: { ...corsHeaders, "Content-Type": "application/json" },
    });
  }

  // Optional filter to run a single provider (debugging)
  let onlyProvider: string | null = null;
  try {
    const body = await req.json();
    onlyProvider = body?.provider || null;
  } catch {
    /* no body */
  }

  // Idempotency: if a sweep is already running (any pending/running rows in
  // Stale-recovery: any pending/running row older than 10 min is from a worker
  // that was killed by the edge runtime. Mark it as failed so neither the UI
  // nor the 409-idempotency check below trips on a phantom "active" sweep.
  const tenMinAgo = new Date(Date.now() - 10 * 60_000).toISOString();
  await adminClient.from("qa_live_runs").update({
    status: "failed",
    error_message: "Stale: previous worker exited without committing status (auto-recovered)",
    completed_at: new Date().toISOString(),
  }).in("status", ["pending", "running"])
    .or(`started_at.lt.${tenMinAgo},started_at.is.null`);

  // Idempotency: if a sweep is genuinely in flight (rows updated within the
  // last 10 min), refuse to start a new one and return the active sweep_id.
  const { data: activeRows } = await adminClient
    .from("qa_live_runs")
    .select("sweep_id, status, started_at")
    .in("status", ["pending", "running"])
    .gte("started_at", tenMinAgo)
    .limit(1);
  if (activeRows && activeRows.length > 0) {
    return new Response(
      JSON.stringify({
        error: "sweep_already_running",
        sweep_id: activeRows[0].sweep_id,
        message: "A sweep is already in progress. Wait for it to finish.",
      }),
      { status: 409, headers: { ...corsHeaders, "Content-Type": "application/json" } },
    );
  }

  // Load budget
  const { data: budget, error: budgetErr } = await adminClient
    .from("qa_live_budget")
    .select("*")
    .order("created_at", { ascending: false })
    .limit(1)
    .maybeSingle();

  if (budgetErr || !budget) {
    return new Response(
      JSON.stringify({ error: "Budget row missing", details: budgetErr?.message }),
      { status: 500, headers: { ...corsHeaders, "Content-Type": "application/json" } },
    );
  }

  const sweepId = crypto.randomUUID();
  const assets = await getTestAssets(adminClient);
  const cap = Number(budget.cap_eur);

  // Reset spent_eur to 0 at the start of each sweep — cap is per-run, not lifetime.
  await adminClient
    .from("qa_live_budget")
    .update({ spent_eur: 0, last_run_at: new Date().toISOString() })
    .eq("id", budget.id);

  const tests = onlyProvider
    ? PROVIDER_MATRIX.filter((t) => t.provider === onlyProvider)
    : PROVIDER_MATRIX;

  // Pre-insert all rows as 'pending' so the UI can render the full grid
  // immediately and poll for status changes.
  const pendingRows = tests.map((t) => ({
    sweep_id: sweepId,
    provider: t.provider,
    model: t.model,
    mode: t.mode,
    status: "pending",
    estimated_cost_eur: t.estimated_cost_eur,
    started_at: new Date().toISOString(),
  }));
  const { error: insertErr } = await adminClient.from("qa_live_runs").insert(pendingRows);
  if (insertErr) {
    return new Response(
      JSON.stringify({ error: "Failed to enqueue sweep", details: insertErr.message }),
      { status: 500, headers: { ...corsHeaders, "Content-Type": "application/json" } },
    );
  }

  // Fire-and-forget background worker. The HTTP response returns immediately.
  // @ts-ignore — EdgeRuntime is provided by Deno Deploy / Supabase Edge runtime
  EdgeRuntime.waitUntil(runSweep(adminClient, sweepId, budget, authHeader, tests, assets));

  return new Response(
    JSON.stringify({
      sweep_id: sweepId,
      status: "running",
      total: tests.length,
      cap_eur: cap,
      message: "Sweep enqueued. Poll qa_live_runs for status.",
    }),
    {
      status: 202,
      headers: { ...corsHeaders, "Content-Type": "application/json" },
    },
  );
});
