/**
 * Picture Studio — prompt & parameter builder (CLIENT view).
 *
 * Deliberately a re-export of the shared module so the "what we send"
 * disclosure in the UI is generated by the exact same code the Edge Functions
 * run. Never fork this logic.
 */

export {
  PICTURE_STYLE_MODIFIERS,
  PICTURE_STYLE_NONE,
  TRANSPARENCY_CAPABLE_TIERS,
  styleModifierFor,
  strengthBucket,
  providerStrength,
  supportsTransparency,
  extractNegativeTerms,
  buildPictureRequest,
  blockingNotice,
} from '../../supabase/functions/_shared/picturePromptBuilder';

export type {
  PictureIntent,
  LocalizedText,
  PromptSegment,
  PromptSegmentSource,
  PictureNotice,
  PictureNoticeCode,
  PicturePromptInput,
  BuiltPictureRequest,
  StrengthBucket,
  AppliedModifier,
  ReferenceInfluence,
  NormalizedPictureRequest,
} from '../../supabase/functions/_shared/picturePromptBuilder';
