import { ShieldAlert } from 'lucide-react';
import { useTranslation } from '@/hooks/useTranslation';

const disclaimerText = {
  en: {
    title: 'Legal Disclaimer — AI-Generated Videos',
    line1: 'All videos are generated by third-party AI models. We assume no liability for the content, accuracy, or legality of the generated material.',
    line2: 'AI-generated videos must be clearly labeled as such when published or shared publicly, in accordance with applicable regulations (e.g. EU AI Act).',
    line3: 'You are solely responsible for ensuring that generated content does not infringe copyrights, trademarks, or personality rights.',
  },
  de: {
    title: 'Haftungsausschluss — KI-generierte Videos',
    line1: 'Alle Videos werden von KI-Modellen Dritter generiert. Wir übernehmen keinerlei Haftung für Inhalt, Richtigkeit oder Rechtmäßigkeit des erzeugten Materials.',
    line2: 'KI-generierte Videos müssen bei Veröffentlichung oder öffentlichem Teilen gemäß geltender Vorschriften (z. B. EU AI Act) eindeutig als KI-generiert gekennzeichnet werden.',
    line3: 'Sie sind allein verantwortlich dafür, dass generierte Inhalte keine Urheber-, Marken- oder Persönlichkeitsrechte verletzen.',
  },
  es: {
    title: 'Aviso Legal — Videos Generados por IA',
    line1: 'Todos los videos son generados por modelos de IA de terceros. No asumimos ninguna responsabilidad por el contenido, la precisión o la legalidad del material generado.',
    line2: 'Los videos generados por IA deben etiquetarse claramente como tales al publicarse o compartirse públicamente, de acuerdo con las regulaciones aplicables (p. ej., EU AI Act).',
    line3: 'Usted es el único responsable de garantizar que el contenido generado no infrinja derechos de autor, marcas comerciales o derechos de personalidad.',
  },
};

export function AIVideoDisclaimer() {
  const { language } = useTranslation();
  const txt = disclaimerText[language as keyof typeof disclaimerText] || disclaimerText.en;

  return (
    <div className="rounded-xl border border-warning/30 bg-warning/5 backdrop-blur-sm p-5">
      <div className="flex items-start gap-3">
        <ShieldAlert className="w-5 h-5 text-warning flex-shrink-0 mt-0.5" />
        <div className="space-y-2">
          <h4 className="font-semibold text-sm text-foreground">{txt.title}</h4>
          <ul className="space-y-1.5 text-xs text-muted-foreground leading-relaxed">
            <li>• {txt.line1}</li>
            <li>• {txt.line2}</li>
            <li>• {txt.line3}</li>
          </ul>
        </div>
      </div>
    </div>
  );
}
