import { useState } from 'react';
import { motion, AnimatePresence } from 'framer-motion';
import { Check, FileText, Image, Play, Music, Download, Sparkles, Layout, MessageCircle, Loader2 } from 'lucide-react';
import { cn } from '@/lib/utils';
import { useAuth } from '@/hooks/useAuth';
import { BriefingStep } from './steps/BriefingStep';
import { ScriptStep } from './steps/ScriptStep';
import { StoryboardStep } from './steps/StoryboardStep';
import { VisualsStep } from './steps/VisualsStep';
import { AnimationStep, type AnimationConfig } from './steps/AnimationStep';
import { AudioStep, type AudioConfig } from './steps/AudioStep';
import { ExportStep } from './steps/ExportStep';
import { ExplainerConsultant } from './ExplainerConsultant';
import { ModeSelector } from './ModeSelector';
import { AutoGenerationProgress } from './AutoGenerationProgress';
import { MarketingStrategyPanel } from './MarketingStrategyPanel';
import type { 
  ExplainerProject, 
  ExplainerBriefing, 
  ExplainerScript, 
  GeneratedAsset, 
  ConsultationResult,
  GenerationMode 
} from '@/types/explainer-studio';

// Steps for manual mode
const STEPS_MANUAL = [
  { id: 'mode-select', label: 'Modus', icon: Sparkles, description: 'Wähle deinen Weg' },
  { id: 'consultation', label: 'Beratung', icon: MessageCircle, description: 'KI-Berater' },
  { id: 'briefing', label: 'Briefing', icon: FileText, description: 'Produkt & Zielgruppe' },
  { id: 'script', label: 'Drehbuch', icon: Sparkles, description: 'KI-generiert' },
  { id: 'storyboard', label: 'Storyboard', icon: Layout, description: 'Szenen bearbeiten' },
  { id: 'visuals', label: 'Visuals', icon: Image, description: 'Assets generieren' },
  { id: 'animation', label: 'Animation', icon: Play, description: 'Bewegung & Übergänge' },
  { id: 'audio', label: 'Audio', icon: Music, description: 'Voice-Over & Musik' },
  { id: 'export', label: 'Export', icon: Download, description: 'Rendern & Download' },
];

// Steps for full-service mode  
const STEPS_FULL_SERVICE = [
  { id: 'mode-select', label: 'Modus', icon: Sparkles, description: 'Wähle deinen Weg' },
  { id: 'consultation', label: 'Beratung', icon: MessageCircle, description: '10-Phasen Interview' },
  { id: 'generating', label: 'KI erstellt', icon: Loader2, description: 'Automatisch' },
  { id: 'preview', label: 'Vorschau', icon: Play, description: 'Prüfen & Anpassen' },
  { id: 'export', label: 'Download', icon: Download, description: '3 Formate' },
];

interface ExplainerWizardProps {
  project?: ExplainerProject;
  onProjectUpdate?: (project: ExplainerProject) => void;
}

export function ExplainerWizard({ project, onProjectUpdate }: ExplainerWizardProps) {
  const { user } = useAuth();
  const [generationMode, setGenerationMode] = useState<GenerationMode | null>(null);
  const [currentStep, setCurrentStep] = useState(0);
  const [isAutoGenerating, setIsAutoGenerating] = useState(false);
  const [consultationResult, setConsultationResult] = useState<ConsultationResult | null>(null);
  const [briefing, setBriefing] = useState<ExplainerBriefing | null>(project?.briefing || null);
  const [script, setScript] = useState<ExplainerScript | null>(project?.script || null);
  const [assets, setAssets] = useState<GeneratedAsset[]>(project?.assets || []);
  const [animationConfig, setAnimationConfig] = useState<AnimationConfig | null>(null);
  const [audioConfig, setAudioConfig] = useState<AudioConfig | null>(null);
  const [storyboardApproved, setStoryboardApproved] = useState(false);
  const [autoGeneratedProject, setAutoGeneratedProject] = useState<any>(null);

  // Select steps based on mode
  const STEPS = generationMode === 'full-service' ? STEPS_FULL_SERVICE : STEPS_MANUAL;

  const canProceed = () => {
    if (!generationMode) return false;
    
    const stepId = STEPS[currentStep]?.id;
    
    switch (stepId) {
      case 'mode-select':
        return generationMode !== null;
      case 'consultation':
        return true;
      case 'briefing':
        return briefing !== null && 
               briefing.productDescription.length >= 20 &&
               briefing.targetAudience.length > 0;
      case 'script':
        return script !== null && script.scenes.length > 0;
      case 'storyboard':
        return storyboardApproved;
      case 'visuals':
        return assets.length >= (script?.scenes.length || 0);
      case 'animation':
        return animationConfig !== null;
      case 'audio':
        return audioConfig !== null && audioConfig.voiceoverUrl !== null;
      case 'export':
      case 'preview':
      case 'generating':
        return true;
      default:
        return false;
    }
  };

  const handleNext = () => {
    if (currentStep < STEPS.length - 1 && canProceed()) {
      setCurrentStep(currentStep + 1);
    }
  };

  const handleBack = () => {
    if (currentStep > 0) {
      setCurrentStep(currentStep - 1);
    }
  };

  const handleModeSelect = (mode: GenerationMode) => {
    setGenerationMode(mode);
    setCurrentStep(1); // Move to consultation step
  };

  const handleConsultationComplete = (result: ConsultationResult) => {
    setConsultationResult(result);
    
    if (generationMode === 'full-service') {
      // Start auto-generation
      setIsAutoGenerating(true);
      setCurrentStep(2); // Move to generating step
    } else {
      // Manual mode - go to briefing
      handleNext();
    }
  };

  const handleConsultationSkip = () => {
    if (generationMode === 'full-service') {
      // Can't skip in full-service - consultation is required
      return;
    }
    // Manual mode - skip to briefing
    setCurrentStep(2);
  };

  const handleAutoGenerationComplete = (project: any) => {
    setAutoGeneratedProject(project);
    setIsAutoGenerating(false);
    
    // Extract data from auto-generated project
    if (project.script) setScript(project.script);
    if (project.assets) setAssets(project.assets);
    if (project.audioConfig) setAudioConfig(project.audioConfig);
    
    setCurrentStep(3); // Move to preview step
  };

  const handleSwitchToManual = (partialProject: any) => {
    setGenerationMode('manual');
    setIsAutoGenerating(false);
    
    // Preserve any generated content
    if (partialProject?.script) setScript(partialProject.script);
    if (partialProject?.assets) setAssets(partialProject.assets);
    
    // Go to appropriate step based on what was generated
    if (partialProject?.script) {
      setCurrentStep(4); // Storyboard step
    } else {
      setCurrentStep(2); // Briefing step
    }
  };

  const handleBriefingComplete = (newBriefing: ExplainerBriefing) => {
    setBriefing(newBriefing);
    handleNext();
  };

  const handleScriptComplete = (newScript: ExplainerScript) => {
    setScript(newScript);
    handleNext();
  };

  const handleStoryboardComplete = (updatedScript: ExplainerScript) => {
    setScript(updatedScript);
    setStoryboardApproved(true);
    handleNext();
  };

  const handleVisualsComplete = (newAssets: GeneratedAsset[]) => {
    setAssets(newAssets);
    handleNext();
  };

  const handleAnimationComplete = (config: AnimationConfig) => {
    setAnimationConfig(config);
    handleNext();
  };

  const handleAudioComplete = (config: AudioConfig) => {
    setAudioConfig(config);
    handleNext();
  };

  // Get current step ID
  const currentStepId = STEPS[currentStep]?.id;

  return (
    <div className="max-w-7xl mx-auto">
      {/* Stepper - only show after mode selection */}
      {generationMode && (
        <div className="mb-8 overflow-x-auto pb-2">
          <div className="flex items-center justify-between min-w-max gap-2">
            {STEPS.map((step, index) => {
              const Icon = step.icon;
              const isActive = index === currentStep;
              const isCompleted = index < currentStep;

              return (
                <div key={step.id} className="flex items-center">
                  <motion.button
                    onClick={() => index < currentStep && setCurrentStep(index)}
                    disabled={index > currentStep}
                    className={cn(
                      'flex items-center gap-2 px-4 py-2.5 rounded-xl transition-all duration-300',
                      'border backdrop-blur-sm',
                      isActive && 'bg-primary/20 border-primary/50 text-primary shadow-[0_0_20px_rgba(245,199,106,0.3)]',
                      isCompleted && 'bg-primary/10 border-primary/30 text-primary cursor-pointer hover:bg-primary/20',
                      !isActive && !isCompleted && 'bg-muted/20 border-white/10 text-muted-foreground'
                    )}
                    whileHover={isCompleted ? { scale: 1.02 } : {}}
                    whileTap={isCompleted ? { scale: 0.98 } : {}}
                  >
                    <div className={cn(
                      'w-8 h-8 rounded-lg flex items-center justify-center',
                      isActive && 'bg-primary text-primary-foreground',
                      isCompleted && 'bg-primary/30 text-primary',
                      !isActive && !isCompleted && 'bg-muted/30 text-muted-foreground'
                    )}>
                      {isCompleted ? (
                        <Check className="h-4 w-4" />
                      ) : (
                        <Icon className={cn("h-4 w-4", step.id === 'generating' && isActive && "animate-spin")} />
                      )}
                    </div>
                    <div className="hidden lg:block text-left">
                      <div className="text-sm font-medium">{step.label}</div>
                      <div className="text-xs text-muted-foreground">{step.description}</div>
                    </div>
                  </motion.button>
                  {index < STEPS.length - 1 && (
                    <div
                      className={cn(
                        'h-px w-6 lg:w-10 mx-1',
                        isCompleted ? 'bg-primary' : 'bg-border'
                      )}
                    />
                  )}
                </div>
              );
            })}
          </div>
        </div>
      )}

      {/* Step Content */}
      <AnimatePresence mode="wait">
        <motion.div
          key={currentStepId}
          initial={{ opacity: 0, y: 20 }}
          animate={{ opacity: 1, y: 0 }}
          exit={{ opacity: 0, y: -20 }}
          transition={{ duration: 0.3 }}
        >
          {/* Mode Selection */}
          {!generationMode && (
            <ModeSelector onSelectMode={handleModeSelect} />
          )}

          {/* Consultation */}
          {currentStepId === 'consultation' && (
            <ExplainerConsultant
              onConsultationComplete={handleConsultationComplete}
              onSkip={handleConsultationSkip}
              mode={generationMode || 'manual'}
            />
          )}

          {/* Auto Generation (Full-Service) */}
          {currentStepId === 'generating' && isAutoGenerating && consultationResult && user && (
            <AutoGenerationProgress
              consultationResult={consultationResult}
              userId={user.id}
              onComplete={handleAutoGenerationComplete}
              onSwitchToManual={handleSwitchToManual}
            />
          )}

          {/* Preview (Full-Service after generation) */}
          {currentStepId === 'preview' && autoGeneratedProject && briefing && script && (
            <div className="space-y-6">
              <MarketingStrategyPanel recommendation={consultationResult!} />
              <ExportStep
                briefing={briefing}
                script={script}
                assets={assets}
                animationConfig={animationConfig || {
                  sceneAnimations: {},
                  globalSettings: { 
                    showSceneTitles: true, 
                    showProgressBar: true, 
                    transitionDuration: 0.5, 
                    textDisplayDuration: 3 
                  },
                  transitions: { type: 'fade', duration: 0.5 }
                }}
                audioConfig={audioConfig || {
                  voiceId: '',
                  voiceName: '',
                  voiceSpeed: 1,
                  voiceoverUrl: autoGeneratedProject.voiceoverUrl || null,
                  backgroundMusicId: null,
                  backgroundMusicUrl: autoGeneratedProject.musicUrl || null,
                  musicVolume: 0.3,
                  voiceVolume: 1,
                  language: 'de',
                  soundEffects: [],
                  sceneVoiceConfigs: []
                }}
                onBack={handleBack}
              />
            </div>
          )}

          {/* Manual Mode Steps */}
          {currentStepId === 'briefing' && (
            <div className="space-y-6">
              {consultationResult && (
                <MarketingStrategyPanel recommendation={consultationResult} />
              )}
              <BriefingStep
                initialBriefing={briefing}
                consultationResult={consultationResult}
                onComplete={handleBriefingComplete}
              />
            </div>
          )}

          {currentStepId === 'script' && briefing && (
            <ScriptStep
              briefing={briefing}
              initialScript={script}
              onComplete={handleScriptComplete}
              onBack={handleBack}
            />
          )}

          {currentStepId === 'storyboard' && briefing && script && (
            <StoryboardStep
              briefing={briefing}
              script={script}
              onComplete={handleStoryboardComplete}
              onBack={handleBack}
            />
          )}

          {currentStepId === 'visuals' && briefing && script && (
            <VisualsStep
              briefing={briefing}
              script={script}
              initialAssets={assets}
              onComplete={handleVisualsComplete}
              onBack={handleBack}
            />
          )}

          {currentStepId === 'animation' && briefing && script && assets.length > 0 && (
            <AnimationStep
              briefing={briefing}
              script={script}
              assets={assets}
              onComplete={handleAnimationComplete}
              onBack={handleBack}
            />
          )}

          {currentStepId === 'audio' && briefing && script && (
            <AudioStep
              briefing={briefing}
              script={script}
              onComplete={handleAudioComplete}
              onBack={handleBack}
            />
          )}

          {currentStepId === 'export' && briefing && script && assets.length > 0 && animationConfig && audioConfig && (
            <ExportStep
              briefing={briefing}
              script={script}
              assets={assets}
              animationConfig={animationConfig}
              audioConfig={audioConfig}
              onBack={handleBack}
            />
          )}
        </motion.div>
      </AnimatePresence>
    </div>
  );
}
